= Migrate existing cluster to the operator

Migrating an existing Apache Pulsar cluster to one controlled by the {pulsar-operator} is a manual process, but the included migration-tool CLI is a great friend to help you migrating your cluster.

== Migration tool

The migration tool is a CLI application that connects to an existing Apache Pulsar cluster and generates a valid and equivalent `PulsarCluster` CRD.
The tool also simulates what would happen if the generated `PulsarCluster` would be submitted. Then it retrieves the kubernetes resources that would be created and compares them with the existing ones, generating a fancy HTML report.
Once the report is generated, is up to you to decide if you want to proceed with the migration or not.

== Prerequisites
* Java 17
* An existing Apache Pulsar cluster
* Download the JAR from the https://github.com/riptano/pulsar-operator/releases[latest release].

== Migrate cluster
. Create an input file called `input-cluster-specs.yaml` with the following content:
+
[source,yaml]
----
context: <context-name>
namespace: <namespace>
clusterName: <cluster-name>
----

.. To retrieve the context-name:
+
[tabs]
====
Helm::
+
--
[source,helm]
----
kubectl config get-contexts
----
--

Result::
+
--
[source,console]
----
CURRENT   NAME                                         CLUSTER                                      AUTHINFO                                     NAMESPACE
*         gke_gcp-techpubs_us-east1-b_pulsar-cluster   gke_gcp-techpubs_us-east1-b_pulsar-cluster   gke_gcp-techpubs_us-east1-b_pulsar-cluster   pulsar-cluster
----
--
====
+
[NOTE]
====
We recommend switching to K8's current context and ensuring connectivity (`kubectl get pods`) before running the migration tool.
====

.. The namespace is the namespace with the Apache Pulsar resources you wish to scan.
.. The clusterName is the prefix of each pod. For example, if the broker pod is `pulsar-prod-cluster-broker-0`, the `clusterName` is `pulsar-prod-cluster`.

. After you've added the retrieved values to input-cluster-specs.yaml, generate the report with:
+
[source,java]
----
java -jar migration-tool.jar generate -i input-cluster-specs.yaml -o output
----

In the logs you'll see a link of the generated report. Open the generated report in your browser and check the differences between the existing cluster and the operator.

Sometimes you might need to change the generated CRD and simulate the migration again. To do that, you can run:
+
[source,java]
----
java -jar migration-tool.jar diff -d output/<context-name>
----



## Migration procedure
Once you're happy with the report, you can proceed with the migration. 
The migration supposes the existing cluster has been created using Helm.

Create a new `values.yaml` file for the operator. Then in the `pulsar-operator.cluster` section copy the crd's spec.
```
pulsar-operator:
    cluster:
        create: true
        name: <cluster-name>
        spec:
            <copy here the spec from the CRD>
```


1. Install the operator release with the above values. 
    ```
    helm install pulsar-operator datastax/pulsar-stack --values <values.yaml>
    ```

2. Wait for the operator to take control of the cluster. Check the PulsarCluster status to be ready. Since each resource will match the existing ones, the following behaviours are expected:
  - The operator will not create any new resource.
  - The operator will not delete any existing resource.
  - The operator will restart every statefulset/deployments. This will be done in a safe manner using the staged upgrades feature of the operator.
3. Delete the existing chart release.
    ```
    kubectl delete secret -l name=<old-release-name>,owner=helm
    ```
4. Cleanup helm annotations and labels from the new values.

   You can safely remove the following annotations:
    - meta.helm.sh/release-name
    - meta.helm.sh/release-namespace

   and labels:
    - app.kubernetes.io/managed-by
    - chart
    - release
    - heritage