= {product}
:navtitle: About {product}

{product} simplifies running https://pulsar.apache.org[{pulsar-reg}] on Kubernetes by applying the familiar https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operator pattern] to the {pulsar-short} components, and horizontally scaling resources up or down based on CPU and memory workloads.

Operating and maintaining {pulsar} clusters traditionally involves complex manual configurations, making it challenging for developers and operators to effectively manage the system's lifecycle. However, with the {product-short}, these complexities are abstracted away, enabling developers to focus on their applications rather than the underlying infrastructure.

Some of the key features and benefits of the {product-short} include:

- **Easy Deployment**: Deploying an {pulsar} cluster on Kubernetes is simplified through declarative configurations and automation provided by the operator.

- **Scalability**: The {product-short} enables effortless scaling of {pulsar-short} clusters by automatically handling the creation and configuration of new {pulsar-short} brokers and bookies as per defined rules. The broker autoscaling is integrated with the {pulsar-short} broker load balancer to make smart resource management decisions, and bookkeepers are scaled up and down based on storage usage in a safe, controlled manner.

- **High Availability**: The operator implements best practices for high availability, ensuring that {pulsar-short} clusters are fault-tolerant and can sustain failures without service disruptions.

- **Lifecycle Management**: The operator takes care of common {pulsar-short} cluster lifecycle tasks, such as cluster creation, upgrade, configuration updates, and graceful shutdowns.

We also offer the xref:getting-started:stack.adoc[{pulsar-stack}] if you're looking for more Kubernetes-native tooling deployed with your {pulsar-short} cluster. Along with the `PulsarCluster` {crd}, {pulsar-stack} also includes:

* {product-short}
* Prometheus Stack (Grafana)
* {pulsar-short} Grafana dashboards
* Cert Manager
* Keycloak

Whether you are a developer looking to leverage the power of {pulsar} in your Kubernetes environment or an operator seeking to streamline the management of {pulsar-short} clusters, the {product-short} provides a robust and user-friendly solution.

This guide offers a starting point for {product-short}.
We will cover installation and deployment, configuration points, and further options for managing {pulsar-short} components with the {product-short}.

[NOTE]
====
If you're upgrading from KAAP v0.1.0 to v0.2.0, you must upgrade the {crd-short} version to `v1beta1`. See xref:getting-started:upgrade-0-2-0.adoc[].
====

== Features

After a new {cr} type is added to your cluster by installing a {crd-short}, you can create instances of the resource based on its specification.
The Kubernetes API can be extended to support the new resource type, automating away the tedious aspects of managing a {pulsar-short} cluster.

* xref:scaling-components:autoscale-bookies.adoc[BookKeeper autoscaler] - Automatically scale the number of bookies based on memory usage.
* xref:scaling-components:autoscale-brokers.adoc[Broker autoscaler] - Automatically scale the number of brokers based on CPU load.
* xref:resource-sets:index.adoc[Rack-aware bookkeeper placement] - Place bookies in different racks to guarantee high availability.
* xref:scaling-components:kafka.adoc[{kafka-short} API] - Use the {starlight-kafka} API to bring your {kafka-short} message traffic to {pulsar-short}.

== How {product-short} makes {pulsar-short} easier

Operators are a common pattern for packaging, deploying, and managing Kubernetes applications.
Operators extend Kubernetes functionality to automate common tasks in stateful applications.
Think of {product-short} as a manager for the individual components of {pulsar-short}. By implementing the `PulsarCluster` {crd-short}, the operator knows enough to manage the deployment, configuration, and scaling of {pulsar-short} components with re-usable and automated tasks, such as:

* Deploying a {pulsar-short} cluster
* Deploying monitoring and logging components
* Autoscaling bookies based on memory usage, or brokers based on CPU load
* Assigning resources to specific availability zones (AZs)

{product-short} is configured, deployed, and packaged with Helm charts and based on the https://quarkiverse.github.io/quarkiverse-docs/quarkus-operator-sdk/dev/index.html[Quarkus Operator SDK].

== {pulsar-short} component architecture

A typical {pulsar-short} cluster *requires* the following components:

* https://pulsar.apache.org/docs/concepts-architecture-overview/#metadata-store[ZooKeeper] - This is the {pulsar-short} metadata store. It stores data about a cluster's configuration, helps the proxy direct messages to the correct broker, and holds Bookie configurations.

* https://pulsar.apache.org/docs/concepts-architecture-overview/#brokers[Broker] - This is the {pulsar-short} message router.

* https://pulsar.apache.org/docs/concepts-architecture-overview/#apache-bookkeeper[BookKeeper (bookie)] - This is the {pulsar-short} data store.
BookKeeper stores message data in a low-latency, resilient way.

In addition to the required components, you might want to include some *optional components*:

* https://bookkeeper.apache.org/docs/admin/autorecovery[BookKeeper AutoRecovery] - This is a {pulsar-short} component that recovers BookKeeper data in the event of a bookie outage.
* https://pulsar.apache.org/docs/concepts-architecture-overview/#pulsar-proxy[{pulsar-short} proxy] - The {pulsar-short} proxy is just that - a proxy that runs at the edge of the cluster with public facing endpoints.
{pulsar-short} proxy also offers special options for cluster extensions, like our [Starlight Suite of APIs].
* https://pulsar.apache.org/docs/functions-worker-run-separately/[Dedicated functions worker(s)] - You can optionally run dedicated function workers in a {pulsar-short} cluster.
* xref:luna-streaming:components:admin-console-tutorial.adoc[{pulsar-short} AdminConsole] - This is an optional web-based admin console for managing {pulsar-short} clusters.
* xref:luna-streaming:components:heartbeat-vm.adoc[{pulsar-short} Heartbeat] - This is an optional component that monitors the health of {pulsar-short} cluster and emits metrics about the cluster that are helpful for observing and debugging issues.
* Prometheus/Grafana/Alert manager stack - This is the default observability stack for a cluster. The {company} {pulsar-short} Helm chart includes pre-made dashboards in Grafana and pre-wires all the metrics scraping.

To enable these optional components, set them in the Helm chart values. For example, to enable the {pulsar-short} Admin Console in your {pulsar-stack} deployment, add the following configuration to your https://github.com/datastax/kaap/blob/main/helm/kaap-stack/values.yaml#L25[values.yaml] file:
[source,yaml]
----
pulsarAdminConsole:
  enabled: true
----

== How {product-short} installs {pulsar-short}

{product-short} can be installed in two ways.

* xref:getting-started:operator.adoc[{product-short}] - Installs just the operator and the `PulsarCluster` {crd-short} into an existing {pulsar-short} cluster.

* xref:getting-started:stack.adoc[{pulsar-stack}] - Installs and deploys the operator, a {pulsar-short} cluster, and a full Prometheus monitoring stack.

[TIP]
====
You can also scan an existing {pulsar-short} cluster and generate an equivalent `PulsarCluster` {crd-short}. For more, see xref:migration:migrate-cluster.adoc[].
====

To get started, see xref:getting-started:index.adoc[Getting Started].


