= {product}
:navtitle: About {product}

{product} simplifies running https://pulsar.apache.org[{pulsar-reg}] on Kubernetes by applying the familiar https://kubernetes.io/docs/concepts/extend-kubernetes/operator/[Operator pattern] to the {pulsar-short} components, and horizontally scaling resources up or down based on CPU and memory workloads.

Operating and maintaining {pulsar} clusters traditionally involves complex manual configurations, making it challenging for developers and operators to effectively manage the system's lifecycle.
However, with the {product-short}, these complexities are abstracted away, enabling developers to focus on their applications rather than the underlying infrastructure.

== Benefits and features

Easy deployment::
Deploying an {pulsar} cluster on Kubernetes is simplified through declarative configurations and automation provided by the operator.
+
Operators are a common pattern for packaging, deploying, and managing Kubernetes applications.
Operators extend Kubernetes functionality to automate common tasks in stateful applications.
Think of {product-short} as a manager for the individual components of {pulsar-short}. By implementing the `PulsarCluster` CRD, the operator knows enough to manage the deployment, configuration, and scaling of {pulsar-short} components with re-usable and automated tasks, such as:
+
--
* Deploying a {pulsar-short} cluster.
* Deploying monitoring and logging components.
* Autoscaling bookies based on memory usage, or brokers based on CPU load.
* Assigning resources to specific availability zones (AZs).
--
+
{product-short} is configured, deployed, and packaged with Helm charts and based on the https://quarkiverse.github.io/quarkiverse-docs/quarkus-operator-sdk/dev/index.html[Quarkus Operator SDK].

Scalability::
The {product-short} enables effortless scaling of {pulsar-short} clusters by automatically handling the creation and configuration of new {pulsar-short} brokers and bookies as per defined rules.
The broker autoscaling is integrated with the {pulsar-short} broker load balancer to make smart resource management decisions, and bookkeepers are scaled up and down based on storage usage in a safe, controlled manner.
+
After a new custom resource (CR) type is added to your cluster by installing a CRD, you can create instances of the resource based on its specification.
The Kubernetes API can be extended to support the new resource type, automating away the tedious aspects of managing a {pulsar-short} cluster:
+
* xref:scaling-components:autoscale-bookies.adoc[]: Automatically scale the number of bookies based on memory usage.
* xref:scaling-components:autoscale-brokers.adoc[Broker autoscaler]: Automatically scale the number of brokers based on CPU load.
* xref:ROOT:resource-sets.adoc[Rack-aware {bookkeeper-short} placement]: Place bookies in different racks to guarantee high availability.
* xref:scaling-components:kafka.adoc[{kafka-short} API]: Use the {starlight-kafka} API to bring your {kafka-short} message traffic to {pulsar-short}.

High availability::
The operator implements best practices for high availability, ensuring that {pulsar-short} clusters are fault-tolerant and can sustain failures without service disruptions.

Lifecycle management::
The operator takes care of common {pulsar-short} cluster lifecycle tasks, such as cluster creation, upgrade, configuration updates, and graceful shutdowns.

Extended management and monitoring with {pulsar-stack}::
The xref:getting-started:stack.adoc[{pulsar-stack}] deploys more Kubernetes-native tooling with your {pulsar-short} cluster.
Along with the `PulsarCluster` custom resource definition (CRD), {pulsar-stack} also includes the following:
+
* {product-short}
* Prometheus Stack (Grafana)
* {pulsar-short} Grafana dashboards
* Cert Manager
* Keycloak

Whether you are a developer looking to leverage the power of {pulsar} in your Kubernetes environment or an operator seeking to streamline the management of {pulsar-short} clusters, the {product-short} provides a robust and user-friendly solution.

This guide offers a starting point for {product-short}.
It covers installation and deployment, configuration points, and further options for managing {pulsar-short} components with the {product-short}.

== {pulsar-short} component architecture

A typical {pulsar-short} cluster requires the following components:

* https://pulsar.apache.org/docs/concepts-architecture-overview/#metadata-store[{zookeeper-reg}]: This is the {pulsar-short} metadata store. It stores data about a cluster's configuration, helps the proxy direct messages to the correct broker, and holds Bookie configurations.
* https://pulsar.apache.org/docs/concepts-architecture-overview/#brokers[Broker]: This is the {pulsar-short} message router.
* https://pulsar.apache.org/docs/concepts-architecture-overview/#apache-bookkeeper[{bookkeeper-short} (bookie)]: This is the {pulsar-short} data store.
{bookkeeper-short} stores message data in a low-latency, resilient way.

In addition to the required components, you can include optional components:

* https://bookkeeper.apache.org/docs/admin/autorecovery[{bookkeeper} AutoRecovery]: This is a {pulsar-short} component that recovers {bookkeeper-short} data in the event of a bookie outage.
* https://pulsar.apache.org/docs/concepts-architecture-overview/#pulsar-proxy[{pulsar-short} proxy]: This is a proxy that runs at the edge of the cluster with public facing endpoints and support for cluster extensions.
* https://pulsar.apache.org/docs/functions-worker-run-separately/[Dedicated functions workers]: You can optionally run dedicated function workers in a {pulsar-short} cluster.
* xref:luna-streaming:components:admin-console-tutorial.adoc[{pulsar-short} AdminConsole]: This is an optional web-based admin console for managing {pulsar-short} clusters.
* xref:luna-streaming:components:heartbeat-vm.adoc[{pulsar-short} Heartbeat]: This is an optional component that monitors the health of {pulsar-short} cluster and emits metrics about the cluster that are helpful for observing and debugging issues.
* Prometheus/Grafana/Alert manager stack: This is the default observability stack for a cluster. The {company} {pulsar-short} Helm chart includes pre-made dashboards in Grafana and pre-wires all the metrics scraping.

== Get started with the {product-short} and {pulsar-stack}

Use Helm to install {product-short} alone or with the extended management and monitoring capabilities of {pulsar-stack}:

* xref:getting-started:operator.adoc[]
* xref:getting-started:stack.adoc[]