= {pulsar-operator}

{pulsar-operator} simplifies running https://pulsar.apache.org[Apache Pulsar] on Kubernetes.

This guide offers a starting point for {pulsar-operator}.
We will cover installation and deployment, configuration points, and further options for managing Pulsar components with the {pulsar-operator}.

Operator is configured, deployed, and packaged with Helm charts.

== How {pulsar-operator} supports Pulsar

Operators are a common pattern for packaging, deploying, and managing Kubernetes applications.
Operators extend Kubernetes functionality to automate common tasks in stateful applications.
Think of {pulsar-operator} as a manager for the individual components of Pulsar. By implementing the pulsarCluster Custom Resource Definition, the operator knows enough to manage the deployment, configuration, and scaling of Pulsar components with re-usable and automated tasks, such as:

* Deploying a Pulsar cluster
* Deploying monitoring and logging components
* Autoscaling bookies based on load
* Assigning resources to specific availability zones (AZs)

== The {pulsar-operator} deployment of Pulsar

// see 6.1. Cluster Operator
{pulsar-operator} comes in two distinct flavors.
You can install just the operator pod into an existing cluster, or you can install Pulsar Stack, which installs and deploys the operator, a Pulsar cluster, and a full Prometheus monitoring stack.

You can also scan an exiting Pulsar cluster and generate an equivalent PulsarCluster CRD.

== CRDs

After a new custom resource type is added to your cluster by installing a CRD, you can create instances of the resource based on its specification.

Autoscalers

Resource sets

Rack awareness

Staged upgrades