= Bastion

v1alpha1

:source-highlighter: highlightjs

:keywords: openapi, rest, Bastion

:specDir: 

:snippetDir: 

:generator-template: v1 2019-12-20

:info-url: https://openapi-generator.tech

:app-name: Bastion



Auto generated from CRD spec





// markup not found, no include::{specDir}intro.adoc[opts=optional]





Version: v1alpha1



Namespace: pulsar.oss.datastax.com



== Bastion [[Bastion]]



[.fields-Bastion]

[cols="2,4"]

|===

| Field| Description



    | *spec* +

            

            <<Bastion_spec,

















Spec







>>

        

    

    | 

    

    | *status* +

            

            <<Bastion_status,

















Status







>>

        

    

    | 

    

|===









=== Spec [[Bastion_spec]]

Complete namespace: Bastion.Spec



[.fields-BastionSpec]

[cols="2,4"]

|===

| Field| Description



    | *bastion* +

            

            <<Bastion_spec_bastion,

















Bastion







>>

        

    

    | 

    

    | *global* +

            

            <<Bastion_spec_global,

















Global







>>

        

    

    | 

    

|===









==== Bastion [[Bastion_spec_bastion]]

Complete namespace: Bastion.Spec.Bastion

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion: {}

----


[.fields-BastionSpecBastion]

[cols="2,4"]

|===

| Field| Description



    | *annotations* +

    



















[]key/value





    | 

    Annotations to add to each resource (except pods).

    | *antiAffinity* +

            

            <<Bastion_spec_bastion_antiAffinity,

















AntiAffinity







>>

        

    

    | 

    

    | *config* +

    



















any





    | 

    Configuration.

    | *env* +

    



















[]<<Bastion_spec_bastion_env,Env>>





    | 

    Additional container env variables.

    | *gracePeriod* +

    







integer

















    | 

    Termination grace period in seconds.

    | *image* +

    





string



















    | 

    Override Pulsar image.

    | *imagePullPolicy* +

    





string



















    | 

    Override image pull policy.

    | *imagePullSecrets* +

    



















[]<<Bastion_spec_bastion_imagePullSecrets,ImagePullSecrets>>





    | 

    Image pull secrets.

    | *initContainers* +

    



















[]<<Bastion_spec_bastion_initContainers,InitContainers>>





    | 

    Init containers

    | *labels* +

    



















[]key/value





    | 

    Labels to add to each resource (except pods).

    | *matchLabels* +

    



















[]key/value





    | 

    Match labels selectors to add to each pod.

    | *nodeAffinity* +

            

            <<Bastion_spec_bastion_nodeAffinity,

















NodeAffinity







>>

        

    

    | 

    

    | *nodeSelectors* +

    



















[]key/value





    | 

    Additional node selectors.

    | *podAnnotations* +

    



















[]key/value





    | 

    Annotations to add to pod.

    | *podLabels* +

    



















[]key/value





    | 

    Labels to add to each pod.

    | *replicas* +

    







integer

















    | 

    Number of desired replicas.

    | *resources* +

            

            <<Bastion_spec_bastion_resources,

















Resources







>>

        

    

    | 

    

    | *sidecars* +

    



















[]<<Bastion_spec_bastion_initContainers,Sidecars>>





    | 

    Sidecar containers

    | *targetProxy* +

    











boolean













    | 

    Indicates to connect to proxy or the broker. The default value depends whether Proxy is deployed or not.

    | *tolerations* +

    



















[]<<Bastion_spec_bastion_tolerations,Tolerations>>





    | 

    Pod tolerations.

|===









==== Antiaffinity [[Bastion_spec_bastion_antiAffinity]]

Complete namespace: Bastion.Spec.Bastion.Antiaffinity

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    antiaffinity: {}

----


[.fields-BastionSpecBastionAntiAffinity]

[cols="2,4"]

|===

| Field| Description



    | *host* +

            

            <<Bastion_spec_bastion_antiAffinity_host,

















Host







>>

        

    

    | 

    

    | *zone* +

            

            <<Bastion_spec_bastion_antiAffinity_zone,

















Zone







>>

        

    

    | 

    

|===









==== Host [[Bastion_spec_bastion_antiAffinity_host]]

Complete namespace: Bastion.Spec.Bastion.Antiaffinity.Host

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    antiaffinity:
      host: {}

----


[.fields-BastionSpecBastionAntiAffinityHost]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

    | *required* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

|===









==== Zone [[Bastion_spec_bastion_antiAffinity_zone]]

Complete namespace: Bastion.Spec.Bastion.Antiaffinity.Zone

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    antiaffinity:
      zone: {}

----


[.fields-BastionSpecBastionAntiAffinityZone]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

    | *required* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

|===









==== Env [[Bastion_spec_bastion_env]]

Complete namespace: Bastion.Spec.Bastion.Env

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    env: {}

----


[.fields-BastionSpecBastionEnv]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

    | *value* +

    





string



















    | 

    

    | *valueFrom* +

            

            <<Bastion_spec_bastion_env_valueFrom,

















ValueFrom







>>

        

    

    | 

    

|===









==== Valuefrom [[Bastion_spec_bastion_env_valueFrom]]

Complete namespace: Bastion.Spec.Bastion.Env.Valuefrom

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    env:
      valuefrom: {}

----


[.fields-BastionSpecBastionEnvValueFrom]

[cols="2,4"]

|===

| Field| Description



    | *configMapKeyRef* +

            

            <<Bastion_spec_bastion_env_valueFrom_configMapKeyRef,

















ConfigMapKeyRef







>>

        

    

    | 

    

    | *fieldRef* +

            

            <<Bastion_spec_bastion_env_valueFrom_fieldRef,

















FieldRef







>>

        

    

    | 

    

    | *resourceFieldRef* +

            

            <<Bastion_spec_bastion_env_valueFrom_resourceFieldRef,

















ResourceFieldRef







>>

        

    

    | 

    

    | *secretKeyRef* +

            

            <<Bastion_spec_bastion_env_valueFrom_configMapKeyRef,

















SecretKeyRef







>>

        

    

    | 

    

|===









==== Configmapkeyref [[Bastion_spec_bastion_env_valueFrom_configMapKeyRef]]

Complete namespace: Bastion.Spec.Bastion.Env.Valuefrom.Configmapkeyref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    env:
      valuefrom:
        configmapkeyref: {}

----


[.fields-BastionSpecBastionEnvValueFromConfigMapKeyRef]

[cols="2,4"]

|===

| Field| Description



    | *key* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

    | *optional* +

    











boolean













    | 

    

|===









==== Fieldref [[Bastion_spec_bastion_env_valueFrom_fieldRef]]

Complete namespace: Bastion.Spec.Bastion.Env.Valuefrom.Fieldref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    env:
      valuefrom:
        fieldref: {}

----


[.fields-BastionSpecBastionEnvValueFromFieldRef]

[cols="2,4"]

|===

| Field| Description



    | *apiVersion* +

    





string



















    | 

    

    | *fieldPath* +

    





string



















    | 

    

|===









==== Resourcefieldref [[Bastion_spec_bastion_env_valueFrom_resourceFieldRef]]

Complete namespace: Bastion.Spec.Bastion.Env.Valuefrom.Resourcefieldref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    env:
      valuefrom:
        resourcefieldref: {}

----


[.fields-BastionSpecBastionEnvValueFromResourceFieldRef]

[cols="2,4"]

|===

| Field| Description



    | *containerName* +

    





string



















    | 

    

    | *divisor* +

            

integer or string

























            

        

    

    | 

    

    | *resource* +

    





string



















    | 

    

|===









==== Imagepullsecrets [[Bastion_spec_bastion_imagePullSecrets]]

Complete namespace: Bastion.Spec.Bastion.Imagepullsecrets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    imagepullsecrets: {}

----


[.fields-BastionSpecBastionImagePullSecrets]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

|===









==== Initcontainers [[Bastion_spec_bastion_initContainers]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers: {}

----


[.fields-BastionSpecBastionInitContainers]

[cols="2,4"]

|===

| Field| Description



    | *args* +

    



















[]

string



    | 

    

    | *command* +

    



















[]

string



    | 

    

    | *env* +

    



















[]<<Bastion_spec_bastion_env,Env>>





    | 

    

    | *envFrom* +

    



















[]<<Bastion_spec_bastion_initContainers_envFrom,EnvFrom>>





    | 

    

    | *image* +

    





string



















    | 

    

    | *imagePullPolicy* +

    





string



















    | 

    

    | *lifecycle* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle,

















Lifecycle







>>

        

    

    | 

    

    | *livenessProbe* +

            

            <<Bastion_spec_bastion_initContainers_livenessProbe,

















LivenessProbe







>>

        

    

    | 

    

    | *name* +

    





string



















    | 

    

    | *ports* +

    



















[]<<Bastion_spec_bastion_initContainers_ports,Ports>>





    | 

    

    | *readinessProbe* +

            

            <<Bastion_spec_bastion_initContainers_livenessProbe,

















ReadinessProbe







>>

        

    

    | 

    

    | *resources* +

            

            <<Bastion_spec_bastion_initContainers_resources,

















Resources







>>

        

    

    | 

    

    | *securityContext* +

            

            <<Bastion_spec_bastion_initContainers_securityContext,

















SecurityContext







>>

        

    

    | 

    

    | *startupProbe* +

            

            <<Bastion_spec_bastion_initContainers_livenessProbe,

















StartupProbe







>>

        

    

    | 

    

    | *stdin* +

    











boolean













    | 

    

    | *stdinOnce* +

    











boolean













    | 

    

    | *terminationMessagePath* +

    





string



















    | 

    

    | *terminationMessagePolicy* +

    





string



















    | 

    

    | *tty* +

    











boolean













    | 

    

    | *volumeDevices* +

    



















[]<<Bastion_spec_bastion_initContainers_volumeDevices,VolumeDevices>>





    | 

    

    | *volumeMounts* +

    



















[]<<Bastion_spec_bastion_initContainers_volumeMounts,VolumeMounts>>





    | 

    

    | *workingDir* +

    





string



















    | 

    

|===









==== Envfrom [[Bastion_spec_bastion_initContainers_envFrom]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Envfrom

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      envfrom: {}

----


[.fields-BastionSpecBastionInitContainersEnvFrom]

[cols="2,4"]

|===

| Field| Description



    | *configMapRef* +

            

            <<Bastion_spec_bastion_initContainers_envFrom_configMapRef,

















ConfigMapRef







>>

        

    

    | 

    

    | *prefix* +

    





string



















    | 

    

    | *secretRef* +

            

            <<Bastion_spec_bastion_initContainers_envFrom_configMapRef,

















SecretRef







>>

        

    

    | 

    

|===









==== Configmapref [[Bastion_spec_bastion_initContainers_envFrom_configMapRef]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Envfrom.Configmapref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      envfrom:
        configmapref: {}

----


[.fields-BastionSpecBastionInitContainersEnvFromConfigMapRef]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

    | *optional* +

    











boolean













    | 

    

|===









==== Lifecycle [[Bastion_spec_bastion_initContainers_lifecycle]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Lifecycle

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      lifecycle: {}

----


[.fields-BastionSpecBastionInitContainersLifecycle]

[cols="2,4"]

|===

| Field| Description



    | *postStart* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart,

















PostStart







>>

        

    

    | 

    

    | *preStop* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart,

















PreStop







>>

        

    

    | 

    

|===









==== Poststart [[Bastion_spec_bastion_initContainers_lifecycle_postStart]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Lifecycle.Poststart

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      lifecycle:
        poststart: {}

----


[.fields-BastionSpecBastionInitContainersLifecyclePostStart]

[cols="2,4"]

|===

| Field| Description



    | *exec* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart_exec,

















Exec







>>

        

    

    | 

    

    | *httpGet* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart_httpGet,

















HttpGet







>>

        

    

    | 

    

    | *tcpSocket* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart_tcpSocket,

















TcpSocket







>>

        

    

    | 

    

|===









==== Exec [[Bastion_spec_bastion_initContainers_lifecycle_postStart_exec]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Lifecycle.Poststart.Exec

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      lifecycle:
        poststart:
          exec: {}

----


[.fields-BastionSpecBastionInitContainersLifecyclePostStartExec]

[cols="2,4"]

|===

| Field| Description



    | *command* +

    



















[]

string



    | 

    

|===









==== Httpget [[Bastion_spec_bastion_initContainers_lifecycle_postStart_httpGet]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Lifecycle.Poststart.Httpget

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      lifecycle:
        poststart:
          httpget: {}

----


[.fields-BastionSpecBastionInitContainersLifecyclePostStartHttpGet]

[cols="2,4"]

|===

| Field| Description



    | *host* +

    





string



















    | 

    

    | *httpHeaders* +

    



















[]<<Bastion_spec_bastion_initContainers_lifecycle_postStart_httpGet_httpHeaders,HttpHeaders>>





    | 

    

    | *path* +

    





string



















    | 

    

    | *port* +

            

integer or string

























            

        

    

    | 

    

    | *scheme* +

    





string



















    | 

    

|===









==== Httpheaders [[Bastion_spec_bastion_initContainers_lifecycle_postStart_httpGet_httpHeaders]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Lifecycle.Poststart.Httpget.Httpheaders

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      lifecycle:
        poststart:
          httpget:
            httpheaders: {}

----


[.fields-BastionSpecBastionInitContainersLifecyclePostStartHttpGetHttpHeaders]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

    | *value* +

    





string



















    | 

    

|===









==== Tcpsocket [[Bastion_spec_bastion_initContainers_lifecycle_postStart_tcpSocket]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Lifecycle.Poststart.Tcpsocket

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      lifecycle:
        poststart:
          tcpsocket: {}

----


[.fields-BastionSpecBastionInitContainersLifecyclePostStartTcpSocket]

[cols="2,4"]

|===

| Field| Description



    | *host* +

    





string



















    | 

    

    | *port* +

            

integer or string

























            

        

    

    | 

    

|===









==== Livenessprobe [[Bastion_spec_bastion_initContainers_livenessProbe]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Livenessprobe

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      livenessprobe: {}

----


[.fields-BastionSpecBastionInitContainersLivenessProbe]

[cols="2,4"]

|===

| Field| Description



    | *exec* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart_exec,

















Exec







>>

        

    

    | 

    

    | *failureThreshold* +

    







integer

















    | 

    

    | *grpc* +

            

            <<Bastion_spec_bastion_initContainers_livenessProbe_grpc,

















Grpc







>>

        

    

    | 

    

    | *httpGet* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart_httpGet,

















HttpGet







>>

        

    

    | 

    

    | *initialDelaySeconds* +

    







integer

















    | 

    

    | *periodSeconds* +

    







integer

















    | 

    

    | *successThreshold* +

    







integer

















    | 

    

    | *tcpSocket* +

            

            <<Bastion_spec_bastion_initContainers_lifecycle_postStart_tcpSocket,

















TcpSocket







>>

        

    

    | 

    

    | *terminationGracePeriodSeconds* +

    







integer

















    | 

    

    | *timeoutSeconds* +

    







integer

















    | 

    

|===









==== Grpc [[Bastion_spec_bastion_initContainers_livenessProbe_grpc]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Livenessprobe.Grpc

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      livenessprobe:
        grpc: {}

----


[.fields-BastionSpecBastionInitContainersLivenessProbeGrpc]

[cols="2,4"]

|===

| Field| Description



    | *port* +

    







integer

















    | 

    

    | *service* +

    





string



















    | 

    

|===









==== Ports [[Bastion_spec_bastion_initContainers_ports]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Ports

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      ports: {}

----


[.fields-BastionSpecBastionInitContainersPorts]

[cols="2,4"]

|===

| Field| Description



    | *containerPort* +

    







integer

















    | 

    

    | *hostIP* +

    





string



















    | 

    

    | *hostPort* +

    







integer

















    | 

    

    | *name* +

    





string



















    | 

    

    | *protocol* +

    





string



















    | 

    

|===









==== Resources [[Bastion_spec_bastion_initContainers_resources]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Resources

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      resources: {}

----


[.fields-BastionSpecBastionInitContainersResources]

[cols="2,4"]

|===

| Field| Description



    | *limits* +

    



















[]

integer or string



    | 

    

    | *requests* +

    



















[]

integer or string



    | 

    

|===









==== Securitycontext [[Bastion_spec_bastion_initContainers_securityContext]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Securitycontext

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      securitycontext: {}

----


[.fields-BastionSpecBastionInitContainersSecurityContext]

[cols="2,4"]

|===

| Field| Description



    | *allowPrivilegeEscalation* +

    











boolean













    | 

    

    | *capabilities* +

            

            <<Bastion_spec_bastion_initContainers_securityContext_capabilities,

















Capabilities







>>

        

    

    | 

    

    | *privileged* +

    











boolean













    | 

    

    | *procMount* +

    





string



















    | 

    

    | *readOnlyRootFilesystem* +

    











boolean













    | 

    

    | *runAsGroup* +

    







integer

















    | 

    

    | *runAsNonRoot* +

    











boolean













    | 

    

    | *runAsUser* +

    







integer

















    | 

    

    | *seLinuxOptions* +

            

            <<Bastion_spec_bastion_initContainers_securityContext_seLinuxOptions,

















SeLinuxOptions







>>

        

    

    | 

    

    | *seccompProfile* +

            

            <<Bastion_spec_bastion_initContainers_securityContext_seccompProfile,

















SeccompProfile







>>

        

    

    | 

    

    | *windowsOptions* +

            

            <<Bastion_spec_bastion_initContainers_securityContext_windowsOptions,

















WindowsOptions







>>

        

    

    | 

    

|===









==== Capabilities [[Bastion_spec_bastion_initContainers_securityContext_capabilities]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Securitycontext.Capabilities

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      securitycontext:
        capabilities: {}

----


[.fields-BastionSpecBastionInitContainersSecurityContextCapabilities]

[cols="2,4"]

|===

| Field| Description



    | *add* +

    



















[]

string



    | 

    

    | *drop* +

    



















[]

string



    | 

    

|===









==== Selinuxoptions [[Bastion_spec_bastion_initContainers_securityContext_seLinuxOptions]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Securitycontext.Selinuxoptions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      securitycontext:
        selinuxoptions: {}

----


[.fields-BastionSpecBastionInitContainersSecurityContextSeLinuxOptions]

[cols="2,4"]

|===

| Field| Description



    | *level* +

    





string



















    | 

    

    | *role* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

    | *user* +

    





string



















    | 

    

|===









==== Seccompprofile [[Bastion_spec_bastion_initContainers_securityContext_seccompProfile]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Securitycontext.Seccompprofile

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      securitycontext:
        seccompprofile: {}

----


[.fields-BastionSpecBastionInitContainersSecurityContextSeccompProfile]

[cols="2,4"]

|===

| Field| Description



    | *localhostProfile* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

|===









==== Windowsoptions [[Bastion_spec_bastion_initContainers_securityContext_windowsOptions]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Securitycontext.Windowsoptions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      securitycontext:
        windowsoptions: {}

----


[.fields-BastionSpecBastionInitContainersSecurityContextWindowsOptions]

[cols="2,4"]

|===

| Field| Description



    | *gmsaCredentialSpec* +

    





string



















    | 

    

    | *gmsaCredentialSpecName* +

    





string



















    | 

    

    | *hostProcess* +

    











boolean













    | 

    

    | *runAsUserName* +

    





string



















    | 

    

|===









==== Volumedevices [[Bastion_spec_bastion_initContainers_volumeDevices]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Volumedevices

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      volumedevices: {}

----


[.fields-BastionSpecBastionInitContainersVolumeDevices]

[cols="2,4"]

|===

| Field| Description



    | *devicePath* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

|===









==== Volumemounts [[Bastion_spec_bastion_initContainers_volumeMounts]]

Complete namespace: Bastion.Spec.Bastion.Initcontainers.Volumemounts

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    initcontainers:
      volumemounts: {}

----


[.fields-BastionSpecBastionInitContainersVolumeMounts]

[cols="2,4"]

|===

| Field| Description



    | *mountPath* +

    





string



















    | 

    

    | *mountPropagation* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *subPath* +

    





string



















    | 

    

    | *subPathExpr* +

    





string



















    | 

    

|===









==== Nodeaffinity [[Bastion_spec_bastion_nodeAffinity]]

Complete namespace: Bastion.Spec.Bastion.Nodeaffinity

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    nodeaffinity: {}

----


[.fields-BastionSpecBastionNodeAffinity]

[cols="2,4"]

|===

| Field| Description



    | *preferredDuringSchedulingIgnoredDuringExecution* +

    



















[]<<Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution,PreferredDuringSchedulingIgnoredDuringExecution>>





    | 

    

    | *requiredDuringSchedulingIgnoredDuringExecution* +

            

            <<Bastion_spec_bastion_nodeAffinity_requiredDuringSchedulingIgnoredDuringExecution,

















RequiredDuringSchedulingIgnoredDuringExecution







>>

        

    

    | 

    

|===









==== Preferredduringschedulingignoredduringexecution [[Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution]]

Complete namespace: Bastion.Spec.Bastion.Nodeaffinity.Preferredduringschedulingignoredduringexecution

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    nodeaffinity:
      preferredduringschedulingignoredduringexecution: {}

----


[.fields-BastionSpecBastionNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution]

[cols="2,4"]

|===

| Field| Description



    | *preference* +

            

            <<Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference,

















Preference







>>

        

    

    | 

    

    | *weight* +

    







integer

















    | 

    

|===









==== Preference [[Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference]]

Complete namespace: Bastion.Spec.Bastion.Nodeaffinity.Preferredduringschedulingignoredduringexecution.Preference

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    nodeaffinity:
      preferredduringschedulingignoredduringexecution:
        preference: {}

----


[.fields-BastionSpecBastionNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference]

[cols="2,4"]

|===

| Field| Description



    | *matchExpressions* +

    



















[]<<Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference_matchExpressions,MatchExpressions>>





    | 

    

    | *matchFields* +

    



















[]<<Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference_matchExpressions,MatchFields>>





    | 

    

|===









==== Matchexpressions [[Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference_matchExpressions]]

Complete namespace: Bastion.Spec.Bastion.Nodeaffinity.Preferredduringschedulingignoredduringexecution.Preference.Matchexpressions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    nodeaffinity:
      preferredduringschedulingignoredduringexecution:
        preference:
          matchexpressions: {}

----


[.fields-BastionSpecBastionNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions]

[cols="2,4"]

|===

| Field| Description



    | *key* +

    





string



















    | 

    

    | *operator* +

    





string



















    | 

    

    | *values* +

    



















[]

string



    | 

    

|===









==== Requiredduringschedulingignoredduringexecution [[Bastion_spec_bastion_nodeAffinity_requiredDuringSchedulingIgnoredDuringExecution]]

Complete namespace: Bastion.Spec.Bastion.Nodeaffinity.Requiredduringschedulingignoredduringexecution

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    nodeaffinity:
      requiredduringschedulingignoredduringexecution: {}

----


[.fields-BastionSpecBastionNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution]

[cols="2,4"]

|===

| Field| Description



    | *nodeSelectorTerms* +

    



















[]<<Bastion_spec_bastion_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference,NodeSelectorTerms>>





    | 

    

|===









==== Resources [[Bastion_spec_bastion_resources]]

Complete namespace: Bastion.Spec.Bastion.Resources

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    resources: {}

----


[.fields-BastionSpecBastionResources]

[cols="2,4"]

|===

| Field| Description



    | *limits* +

    



















[]

integer or string



    | 

    

    | *requests* +

    



















[]

integer or string



    | 

    

|===









==== Tolerations [[Bastion_spec_bastion_tolerations]]

Complete namespace: Bastion.Spec.Bastion.Tolerations

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  bastion:
    tolerations: {}

----


[.fields-BastionSpecBastionTolerations]

[cols="2,4"]

|===

| Field| Description



    | *effect* +

    





string



















    | 

    

    | *key* +

    





string



















    | 

    

    | *operator* +

    





string



















    | 

    

    | *tolerationSeconds* +

    







integer

















    | 

    

    | *value* +

    





string



















    | 

    

|===









==== Global [[Bastion_spec_global]]

Complete namespace: Bastion.Spec.Global

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global: {}

----


[.fields-BastionSpecGlobal]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | _(Optional)_ + 

    Pulsar cluster name.

    | *antiAffinity* +

            

            <<Bastion_spec_global_antiAffinity,

















AntiAffinity







>>

        

    

    | 

    

    | *auth* +

            

            <<Bastion_spec_global_auth,

















Auth







>>

        

    

    | 

    

    | *components* +

            

            <<Bastion_spec_global_components,

















Components







>>

        

    

    | 

    

    | *dnsConfig* +

            

            <<Bastion_spec_global_dnsConfig,

















DnsConfig







>>

        

    

    | 

    

    | *dnsName* +

    





string



















    | 

    Public dns name for the cluster&#39;s load balancer.

    | *image* +

    





string



















    | 

    Default Pulsar image to use. Any components can be configured to use a different image.

    | *imagePullPolicy* +

    





string



















    | 

    Default Pulsar image pull policy to use. Any components can be configured to use a different image pull policy. Default value is &#39;IfNotPresent&#39;.

    | *kubernetesClusterDomain* +

    





string



















    | 

    The domain name for your kubernetes cluster. This domain is documented here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1 . It&#39;s used to fully qualify service names when configuring Pulsar. The default value is &#39;cluster.local&#39;. 

    | *nodeSelectors* +

    



















[]key/value





    | 

    Global node selector. If set, this will apply to all the components.

    | *persistence* +

    











boolean













    | 

    If persistence is enabled, components that has state will be deployed with PersistentVolumeClaims, otherwise, for test purposes, they will be deployed with emptyDir 

    | *priorityClassName* +

    





string



















    | 

    Priority class name to attach to each pod.

    | *racks* +

    



















[]





    | 

    Racks configuration.

    | *resourceSets* +

    



















[]





    | 

    Resource sets.

    | *restartOnConfigMapChange* +

    











boolean













    | 

    By default, Kubernetes will not restart pods when only their configmap is changed. This setting will restart pods when their configmap is changed using an annotation that calculates the checksum of the configmap. 

    | *storage* +

            

            <<Bastion_spec_global_storage,

















Storage







>>

        

    

    | 

    

    | *tls* +

            

            <<Bastion_spec_global_tls,

















Tls







>>

        

    

    | 

    

    | *zookeeperPlainSslStorePassword* +

    











boolean













    | 

    Use plain password in zookeeper server and client configuration. Default is false. Old versions of Apache Zookeeper (&lt;3.8.0) does not support getting password from file. In that case, set this to true.

|===









==== Antiaffinity [[Bastion_spec_global_antiAffinity]]

Complete namespace: Bastion.Spec.Global.Antiaffinity

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    antiaffinity: {}

----


[.fields-BastionSpecGlobalAntiAffinity]

[cols="2,4"]

|===

| Field| Description



    | *host* +

            

            <<Bastion_spec_bastion_antiAffinity_host,

















Host







>>

        

    

    | 

    

    | *zone* +

            

            <<Bastion_spec_bastion_antiAffinity_zone,

















Zone







>>

        

    

    | 

    

|===









==== Auth [[Bastion_spec_global_auth]]

Complete namespace: Bastion.Spec.Global.Auth

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    auth: {}

----


[.fields-BastionSpecGlobalAuth]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable authentication in the cluster. Default is &#39;false&#39;.

    | *token* +

            

            <<Bastion_spec_global_auth_token,

















Token







>>

        

    

    | 

    

|===









==== Token [[Bastion_spec_global_auth_token]]

Complete namespace: Bastion.Spec.Global.Auth.Token

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    auth:
      token: {}

----


[.fields-BastionSpecGlobalAuthToken]

[cols="2,4"]

|===

| Field| Description



    | *initialize* +

    











boolean













    | 

    Initialize Secrets with new pair of keys and tokens for the super user roles. The generated Secret name is &#39;token-&lt;role&gt;&#39;.

    | *privateKeyFile* +

    





string



















    | 

    Private key file name stored in the Secret. Default is &#39;my-private.key&#39;

    | *proxyRoles* +

    



















[]

string



    | 

    Proxy roles.

    | *publicKeyFile* +

    





string



















    | 

    Public key file name stored in the Secret. Default is &#39;my-public.key&#39;

    | *superUserRoles* +

    



















[]

string



    | 

    Super user roles.

|===









==== Components [[Bastion_spec_global_components]]

Complete namespace: Bastion.Spec.Global.Components

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    components: {}

----


[.fields-BastionSpecGlobalComponents]

[cols="2,4"]

|===

| Field| Description



    | *autorecoveryBaseName* +

    





string



















    | 

    Autorecovery base name. Default value is &#39;autorecovery&#39;.

    | *bastionBaseName* +

    





string



















    | 

    Bastion base name. Default value is &#39;bastion&#39;.

    | *bookkeeperBaseName* +

    





string



















    | 

    BookKeeper base name. Default value is &#39;bookkeeper&#39;.

    | *brokerBaseName* +

    





string



















    | 

    Broker base name. Default value is &#39;broker&#39;.

    | *functionsWorkerBaseName* +

    





string



















    | 

    Functions Worker base name. Default value is &#39;function&#39;.

    | *proxyBaseName* +

    





string



















    | 

    Proxy base name. Default value is &#39;proxy&#39;.

    | *zookeeperBaseName* +

    





string



















    | 

    Zookeeper base name. Default value is &#39;zookeeper&#39;.

|===









==== Dnsconfig [[Bastion_spec_global_dnsConfig]]

Complete namespace: Bastion.Spec.Global.Dnsconfig

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    dnsconfig: {}

----


[.fields-BastionSpecGlobalDnsConfig]

[cols="2,4"]

|===

| Field| Description



    | *nameservers* +

    



















[]

string



    | 

    

    | *options* +

    



















[]<<Bastion_spec_bastion_initContainers_lifecycle_postStart_httpGet_httpHeaders,Options>>





    | 

    

    | *searches* +

    



















[]

string



    | 

    

|===









==== Racks [[Bastion_spec_global_racks]]

Complete namespace: Bastion.Spec.Global.Racks

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    racks: {}

----


[.fields-BastionSpecGlobalRacks]

[cols="2,4"]

|===

| Field| Description



    | *host* +

            

            <<Bastion_spec_global_racks_host,

















Host







>>

        

    

    | 

    

    | *zone* +

            

            <<Bastion_spec_global_racks_zone,

















Zone







>>

        

    

    | 

    

|===









==== Host [[Bastion_spec_global_racks_host]]

Complete namespace: Bastion.Spec.Global.Racks.Host

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    racks:
      host: {}

----


[.fields-BastionSpecGlobalRacksHost]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable the rack affinity rules.

    | *requireRackAffinity* +

    











boolean













    | 

    Indicates if the podAffinity rules will be enforced. Default is false. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

    | *requireRackAntiAffinity* +

    











boolean













    | 

    Indicates if the podAntiAffinity rules will be enforced. Default is true. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

|===









==== Zone [[Bastion_spec_global_racks_zone]]

Complete namespace: Bastion.Spec.Global.Racks.Zone

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    racks:
      zone: {}

----


[.fields-BastionSpecGlobalRacksZone]

[cols="2,4"]

|===

| Field| Description



    | *enableHostAntiAffinity* +

    











boolean













    | 

    Enable the host anti affinity. If set, all the pods of the same rack will deployed on different nodes of the same zone.Default is true.

    | *enabled* +

    











boolean













    | 

    Enable the rack affinity rules.

    | *requireRackAffinity* +

    











boolean













    | 

    Indicates if the podAffinity rules will be enforced. Default is false. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

    | *requireRackAntiAffinity* +

    











boolean













    | 

    Indicates if the podAntiAffinity rules will be enforced. Default is true. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

    | *requireRackHostAntiAffinity* +

    











boolean













    | 

    Indicates if the podAntiAffinity rules will be enforced for the host. Default is true. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

|===









==== Resourcesets [[Bastion_spec_global_resourceSets]]

Complete namespace: Bastion.Spec.Global.Resourcesets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    resourcesets: {}

----


[.fields-BastionSpecGlobalResourceSets]

[cols="2,4"]

|===

| Field| Description



    | *rack* +

    





string



















    | 

    Place this resource set to a specific rack, defined at .global.racks.

|===









==== Storage [[Bastion_spec_global_storage]]

Complete namespace: Bastion.Spec.Global.Storage

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    storage: {}

----


[.fields-BastionSpecGlobalStorage]

[cols="2,4"]

|===

| Field| Description



    | *existingStorageClassName* +

    





string



















    | 

    Indicates if an already existing storage class should be used.

    | *storageClass* +

            

            <<Bastion_spec_global_storage_storageClass,

















StorageClass







>>

        

    

    | 

    

|===









==== Storageclass [[Bastion_spec_global_storage_storageClass]]

Complete namespace: Bastion.Spec.Global.Storage.Storageclass

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    storage:
      storageclass: {}

----


[.fields-BastionSpecGlobalStorageStorageClass]

[cols="2,4"]

|===

| Field| Description



    | *extraParams* +

    



















[]key/value





    | 

    Adds extra parameters for the StorageClass.

    | *fsType* +

    





string



















    | 

    Indicates the &#39;fsType&#39; parameter for the StorageClass.

    | *provisioner* +

    





string



















    | 

    Indicates the provisioner property for the StorageClass.

    | *reclaimPolicy* +

    





string



















    | 

    Indicates the reclaimPolicy property for the StorageClass.

    | *type* +

    





string



















    | 

    Indicates the &#39;type&#39; parameter for the StorageClass.

|===









==== Tls [[Bastion_spec_global_tls]]

Complete namespace: Bastion.Spec.Global.Tls

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls: {}

----


[.fields-BastionSpecGlobalTls]

[cols="2,4"]

|===

| Field| Description



    | *autorecovery* +

            

            <<Bastion_spec_global_tls_autorecovery,

















Autorecovery







>>

        

    

    | 

    

    | *bookkeeper* +

            

            <<Bastion_spec_global_tls_bookkeeper,

















Bookkeeper







>>

        

    

    | 

    

    | *broker* +

            

            <<Bastion_spec_global_tls_broker,

















Broker







>>

        

    

    | 

    

    | *brokerResourceSets* +

    



















[]





    | 

    TLS configurations related to the Broker resource sets.

    | *caPath* +

    





string



















    | 

    Path in the container filesystem where the TLS CA certificates are retrieved. It has to point to a certificate file. The default value is /etc/ssl/certs/ca-certificates.crt.

    | *certProvisioner* +

            

            <<Bastion_spec_global_tls_certProvisioner,

















CertProvisioner







>>

        

    

    | 

    

    | *defaultSecretName* +

    





string



















    | 

    Secret name used by each component to load TLS certificates. Each component can load a different secret by setting the &#39;secretName&#39; entry in the tls component spec.

    | *enabled* +

    











boolean













    | 

    Global switch to turn on or off the TLS configurations. Additionally, you have configure each component section.

    | *functionsWorker* +

            

            <<Bastion_spec_global_tls_functionsWorker,

















FunctionsWorker







>>

        

    

    | 

    

    | *proxy* +

            

            <<Bastion_spec_global_tls_proxy,

















Proxy







>>

        

    

    | 

    

    | *proxyResourceSets* +

    



















[]





    | 

    TLS configurations related to the Proxy resource sets.

    | *ssCa* +

            

            <<Bastion_spec_global_tls_ssCa,

















SsCa







>>

        

    

    | 

    

    | *zookeeper* +

            

            <<Bastion_spec_global_tls_zookeeper,

















Zookeeper







>>

        

    

    | 

    

|===









==== Autorecovery [[Bastion_spec_global_tls_autorecovery]]

Complete namespace: Bastion.Spec.Global.Tls.Autorecovery

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      autorecovery: {}

----


[.fields-BastionSpecGlobalTlsAutorecovery]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Bookkeeper [[Bastion_spec_global_tls_bookkeeper]]

Complete namespace: Bastion.Spec.Global.Tls.Bookkeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      bookkeeper: {}

----


[.fields-BastionSpecGlobalTlsBookkeeper]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Broker [[Bastion_spec_global_tls_broker]]

Complete namespace: Bastion.Spec.Global.Tls.Broker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      broker: {}

----


[.fields-BastionSpecGlobalTlsBroker]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Brokerresourcesets [[Bastion_spec_global_tls_brokerResourceSets]]

Complete namespace: Bastion.Spec.Global.Tls.Brokerresourcesets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      brokerresourcesets: {}

----


[.fields-BastionSpecGlobalTlsBrokerResourceSets]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Certprovisioner [[Bastion_spec_global_tls_certProvisioner]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner: {}

----


[.fields-BastionSpecGlobalTlsCertProvisioner]

[cols="2,4"]

|===

| Field| Description



    | *selfSigned* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned,

















SelfSigned







>>

        

    

    | 

    

|===









==== Selfsigned [[Bastion_spec_global_tls_certProvisioner_selfSigned]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSigned]

[cols="2,4"]

|===

| Field| Description



    | *autorecovery* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery,

















Autorecovery







>>

        

    

    | 

    

    | *bookkeeper* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_bookkeeper,

















Bookkeeper







>>

        

    

    | 

    

    | *broker* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_broker,

















Broker







>>

        

    

    | 

    

    | *caSecretName* +

    





string



















    | 

    Secret where to store the root CA certificate.

    | *enabled* +

    











boolean













    | 

    Generate self signed certificates for broker, proxy and functions worker.

    | *functionsWorker* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_functionsWorker,

















FunctionsWorker







>>

        

    

    | 

    

    | *includeDns* +

    











boolean













    | 

    Include dns name in the DNS names covered by the certificate.

    | *perComponent* +

    











boolean













    | 

    Generate a different certificate for each component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

    | *proxy* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_proxy,

















Proxy







>>

        

    

    | 

    

    | *zookeeper* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_zookeeper,

















Zookeeper







>>

        

    

    | 

    

|===









==== Autorecovery [[Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Autorecovery

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          autorecovery: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedAutorecovery]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Privatekey [[Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Autorecovery.Privatekey

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          autorecovery:
            privatekey: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedAutorecoveryPrivateKey]

[cols="2,4"]

|===

| Field| Description



    | *algorithm* +

    





string



















    | 

    

    | *encoding* +

    





string



















    | 

    

    | *rotationPolicy* +

    





string



















    | 

    

    | *size* +

    







integer

















    | 

    

|===









==== Bookkeeper [[Bastion_spec_global_tls_certProvisioner_selfSigned_bookkeeper]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Bookkeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          bookkeeper: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedBookkeeper]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Broker [[Bastion_spec_global_tls_certProvisioner_selfSigned_broker]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Broker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          broker: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedBroker]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Functionsworker [[Bastion_spec_global_tls_certProvisioner_selfSigned_functionsWorker]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Functionsworker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          functionsworker: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedFunctionsWorker]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Proxy [[Bastion_spec_global_tls_certProvisioner_selfSigned_proxy]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Proxy

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          proxy: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedProxy]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Zookeeper [[Bastion_spec_global_tls_certProvisioner_selfSigned_zookeeper]]

Complete namespace: Bastion.Spec.Global.Tls.Certprovisioner.Selfsigned.Zookeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          zookeeper: {}

----


[.fields-BastionSpecGlobalTlsCertProvisionerSelfSignedZookeeper]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<Bastion_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Functionsworker [[Bastion_spec_global_tls_functionsWorker]]

Complete namespace: Bastion.Spec.Global.Tls.Functionsworker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      functionsworker: {}

----


[.fields-BastionSpecGlobalTlsFunctionsWorker]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *enabledWithBroker* +

    











boolean













    | 

    Enable TLS for the functions worker to broker connections.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Proxy [[Bastion_spec_global_tls_proxy]]

Complete namespace: Bastion.Spec.Global.Tls.Proxy

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      proxy: {}

----


[.fields-BastionSpecGlobalTlsProxy]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *enabledWithBroker* +

    











boolean













    | 

    Enable TLS for the proxy to broker connections.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Proxyresourcesets [[Bastion_spec_global_tls_proxyResourceSets]]

Complete namespace: Bastion.Spec.Global.Tls.Proxyresourcesets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      proxyresourcesets: {}

----


[.fields-BastionSpecGlobalTlsProxyResourceSets]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *enabledWithBroker* +

    











boolean













    | 

    Enable TLS for the proxy to broker connections.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Ssca [[Bastion_spec_global_tls_ssCa]]

Complete namespace: Bastion.Spec.Global.Tls.Ssca

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      ssca: {}

----


[.fields-BastionSpecGlobalTlsSsCa]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Zookeeper [[Bastion_spec_global_tls_zookeeper]]

Complete namespace: Bastion.Spec.Global.Tls.Zookeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      zookeeper: {}

----


[.fields-BastionSpecGlobalTlsZookeeper]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









=== Status [[Bastion_status]]

Complete namespace: Bastion.Status



[.fields-BastionStatus]

[cols="2,4"]

|===

| Field| Description



    | *conditions* +

    



















[]<<Bastion_status_conditions,Conditions>>





    | 

    Conditions:  1. Condition Ready: possible status are True or False. If False, the reason contains the error message.

    | *lastApplied* +

    





string



















    | 

    Last spec applied.

|===









==== Conditions [[Bastion_status_conditions]]

Complete namespace: Bastion.Status.Conditions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bastion
metadata:
  name: example-pulsarcluster
spec:
  conditions: {}

----


[.fields-BastionStatusConditions]

[cols="2,4"]

|===

| Field| Description



    | *lastTransitionTime* +

    





string



















    | 

    

    | *message* +

    





string



















    | 

    

    | *observedGeneration* +

    







integer

















    | 

    

    | *reason* +

    





string



















    | 

    

    | *status* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

|===

