= BookKeeper

v1alpha1

:source-highlighter: highlightjs

:keywords: openapi, rest, BookKeeper

:specDir: 

:snippetDir: 

:generator-template: v1 2019-12-20

:info-url: https://openapi-generator.tech

:app-name: BookKeeper



Auto generated from CRD spec





// markup not found, no include::{specDir}intro.adoc[opts=optional]





Version: v1alpha1



Namespace: pulsar.oss.datastax.com



== Bookkeeper [[BookKeeper]]



[.fields-BookKeeper]

[cols="2,4"]

|===

| Field| Description



    | *spec* +

            

            <<BookKeeper_spec,

















Spec







>>

        

    

    | 

    

    | *status* +

            

            <<BookKeeper_status,

















Status







>>

        

    

    | 

    

|===









=== Spec [[BookKeeper_spec]]

Complete namespace: Bookkeeper.Spec



[.fields-BookKeeperSpec]

[cols="2,4"]

|===

| Field| Description



    | *bookkeeper* +

            

            <<BookKeeper_spec_bookkeeper,

















Bookkeeper







>>

        

    

    | 

    

    | *global* +

            

            <<BookKeeper_spec_global,

















Global







>>

        

    

    | 

    

|===









==== Bookkeeper [[BookKeeper_spec_bookkeeper]]

Complete namespace: Bookkeeper.Spec.Bookkeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper: {}

----


[.fields-BookKeeperSpecBookkeeper]

[cols="2,4"]

|===

| Field| Description



    | *additionalVolumes* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes,

















AdditionalVolumes







>>

        

    

    | 

    

    | *annotations* +

    



















[]key/value





    | 

    Annotations to add to each resource (except pods).

    | *antiAffinity* +

            

            <<BookKeeper_spec_bookkeeper_antiAffinity,

















AntiAffinity







>>

        

    

    | 

    

    | *autoRackConfig* +

            

            <<BookKeeper_spec_bookkeeper_autoRackConfig,

















AutoRackConfig







>>

        

    

    | 

    

    | *autoscaler* +

            

            <<BookKeeper_spec_bookkeeper_autoscaler,

















Autoscaler







>>

        

    

    | 

    

    | *cleanUpPvcs* +

    











boolean













    | 

    Cleanup PVCs after the bookie has been removed.

    | *config* +

    



















any





    | 

    Configuration.

    | *env* +

    



















[]<<BookKeeper_spec_bookkeeper_env,Env>>





    | 

    Additional container env variables.

    | *gracePeriod* +

    







integer

















    | 

    Termination grace period in seconds.

    | *image* +

    





string



















    | 

    Override Pulsar image.

    | *imagePullPolicy* +

    





string



















    | 

    Override image pull policy.

    | *imagePullSecrets* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,ImagePullSecrets>>





    | 

    Image pull secrets.

    | *initContainers* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers,InitContainers>>





    | 

    Init containers

    | *labels* +

    



















[]key/value





    | 

    Labels to add to each resource (except pods).

    | *matchLabels* +

    



















[]key/value





    | 

    Match labels selectors to add to each pod.

    | *nodeAffinity* +

            

            <<BookKeeper_spec_bookkeeper_nodeAffinity,

















NodeAffinity







>>

        

    

    | 

    

    | *nodeSelectors* +

    



















[]key/value





    | 

    Additional node selectors.

    | *overrideResourceName* +

    





string



















    | 

    Override the resource names generated by the operator.

    | *pdb* +

            

            <<BookKeeper_spec_bookkeeper_pdb,

















Pdb







>>

        

    

    | 

    

    | *podAnnotations* +

    



















[]key/value





    | 

    Annotations to add to pod.

    | *podLabels* +

    



















[]key/value





    | 

    Labels to add to each pod.

    | *podManagementPolicy* +

    





string



















    | 

    Pod management policy. Default value is &#39;Parallel&#39;.

    | *probes* +

            

            <<BookKeeper_spec_bookkeeper_probes,

















Probes







>>

        

    

    | 

    

    | *pvcPrefix* +

    





string



















    | 

    Prefix for each PVC created.

    | *replicas* +

    







integer

















    | 

    Number of desired replicas.

    | *resources* +

            

            <<BookKeeper_spec_bookkeeper_resources,

















Resources







>>

        

    

    | 

    

    | *service* +

            

            <<BookKeeper_spec_bookkeeper_service,

















Service







>>

        

    

    | 

    

    | *sets* +

    



















[]





    | 

    Bookie sets.

    | *setsUpdateStrategy* +

    





string



















    | 

    Sets update strategy. &#39;RollingUpdate&#39; or &#39;Parallel&#39;. Default is &#39;RollingUpdate&#39;.

    | *sidecars* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers,Sidecars>>





    | 

    Sidecar containers

    | *tolerations* +

    



















[]<<BookKeeper_spec_bookkeeper_sets_tolerations,Tolerations>>





    | 

    Pod tolerations.

    | *updateStrategy* +

            

            <<BookKeeper_spec_bookkeeper_sets_updateStrategy,

















UpdateStrategy







>>

        

    

    | 

    

    | *volumes* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes,

















Volumes







>>

        

    

    | 

    

|===









==== Additionalvolumes [[BookKeeper_spec_bookkeeper_additionalVolumes]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumes]

[cols="2,4"]

|===

| Field| Description



    | *mounts* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_mounts,Mounts>>





    | 

    Mount points for the additional volumes

    | *volumes* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes,Volumes>>





    | 

    Additional volumes to be mounted to the pod

|===









==== Mounts [[BookKeeper_spec_bookkeeper_additionalVolumes_mounts]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Mounts

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      mounts: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesMounts]

[cols="2,4"]

|===

| Field| Description



    | *mountPath* +

    





string



















    | 

    

    | *mountPropagation* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *subPath* +

    





string



















    | 

    

    | *subPathExpr* +

    





string



















    | 

    

|===









==== Volumes [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumes]

[cols="2,4"]

|===

| Field| Description



    | *awsElasticBlockStore* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_awsElasticBlockStore,

















AwsElasticBlockStore







>>

        

    

    | 

    

    | *azureDisk* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_azureDisk,

















AzureDisk







>>

        

    

    | 

    

    | *azureFile* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_azureFile,

















AzureFile







>>

        

    

    | 

    

    | *cephfs* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs,

















Cephfs







>>

        

    

    | 

    

    | *cinder* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cinder,

















Cinder







>>

        

    

    | 

    

    | *configMap* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_configMap,

















ConfigMap







>>

        

    

    | 

    

    | *csi* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_csi,

















Csi







>>

        

    

    | 

    

    | *downwardAPI* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI,

















DownwardAPI







>>

        

    

    | 

    

    | *emptyDir* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_emptyDir,

















EmptyDir







>>

        

    

    | 

    

    | *ephemeral* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral,

















Ephemeral







>>

        

    

    | 

    

    | *fc* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_fc,

















Fc







>>

        

    

    | 

    

    | *flexVolume* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_flexVolume,

















FlexVolume







>>

        

    

    | 

    

    | *flocker* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_flocker,

















Flocker







>>

        

    

    | 

    

    | *gcePersistentDisk* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_gcePersistentDisk,

















GcePersistentDisk







>>

        

    

    | 

    

    | *gitRepo* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_gitRepo,

















GitRepo







>>

        

    

    | 

    

    | *glusterfs* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_glusterfs,

















Glusterfs







>>

        

    

    | 

    

    | *hostPath* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_hostPath,

















HostPath







>>

        

    

    | 

    

    | *iscsi* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_iscsi,

















Iscsi







>>

        

    

    | 

    

    | *name* +

    





string



















    | 

    

    | *nfs* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_nfs,

















Nfs







>>

        

    

    | 

    

    | *persistentVolumeClaim* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_persistentVolumeClaim,

















PersistentVolumeClaim







>>

        

    

    | 

    

    | *photonPersistentDisk* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_photonPersistentDisk,

















PhotonPersistentDisk







>>

        

    

    | 

    

    | *portworxVolume* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_portworxVolume,

















PortworxVolume







>>

        

    

    | 

    

    | *projected* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected,

















Projected







>>

        

    

    | 

    

    | *quobyte* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_quobyte,

















Quobyte







>>

        

    

    | 

    

    | *rbd* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_rbd,

















Rbd







>>

        

    

    | 

    

    | *scaleIO* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_scaleIO,

















ScaleIO







>>

        

    

    | 

    

    | *secret* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_secret,

















Secret







>>

        

    

    | 

    

    | *storageos* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_storageos,

















Storageos







>>

        

    

    | 

    

    | *vsphereVolume* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_vsphereVolume,

















VsphereVolume







>>

        

    

    | 

    

|===









==== Awselasticblockstore [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_awsElasticBlockStore]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Awselasticblockstore

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        awselasticblockstore: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesAwsElasticBlockStore]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *partition* +

    







integer

















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *volumeID* +

    





string



















    | 

    

|===









==== Azuredisk [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_azureDisk]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Azuredisk

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        azuredisk: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesAzureDisk]

[cols="2,4"]

|===

| Field| Description



    | *cachingMode* +

    





string



















    | 

    

    | *diskName* +

    





string



















    | 

    

    | *diskURI* +

    





string



















    | 

    

    | *fsType* +

    





string



















    | 

    

    | *kind* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

|===









==== Azurefile [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_azureFile]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Azurefile

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        azurefile: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesAzureFile]

[cols="2,4"]

|===

| Field| Description



    | *readOnly* +

    











boolean













    | 

    

    | *secretName* +

    





string



















    | 

    

    | *shareName* +

    





string



















    | 

    

|===









==== Cephfs [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Cephfs

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        cephfs: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesCephfs]

[cols="2,4"]

|===

| Field| Description



    | *monitors* +

    



















[]

string



    | 

    

    | *path* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretFile* +

    





string



















    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

    | *user* +

    





string



















    | 

    

|===









==== Secretref [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Cephfs.Secretref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        cephfs:
          secretref: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesCephfsSecretRef]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

|===









==== Cinder [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cinder]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Cinder

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        cinder: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesCinder]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

    | *volumeID* +

    





string



















    | 

    

|===









==== Configmap [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_configMap]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Configmap

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        configmap: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesConfigMap]

[cols="2,4"]

|===

| Field| Description



    | *defaultMode* +

    







integer

















    | 

    

    | *items* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_configMap_items,Items>>





    | 

    

    | *name* +

    





string



















    | 

    

    | *optional* +

    











boolean













    | 

    

|===









==== Items [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_configMap_items]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Configmap.Items

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        configmap:
          items: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesConfigMapItems]

[cols="2,4"]

|===

| Field| Description



    | *key* +

    





string



















    | 

    

    | *mode* +

    







integer

















    | 

    

    | *path* +

    





string



















    | 

    

|===









==== Csi [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_csi]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Csi

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        csi: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesCsi]

[cols="2,4"]

|===

| Field| Description



    | *driver* +

    





string



















    | 

    

    | *fsType* +

    





string



















    | 

    

    | *nodePublishSecretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















NodePublishSecretRef







>>

        

    

    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *volumeAttributes* +

    



















[]key/value





    | 

    

|===









==== Downwardapi [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Downwardapi

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        downwardapi: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesDownwardAPI]

[cols="2,4"]

|===

| Field| Description



    | *defaultMode* +

    







integer

















    | 

    

    | *items* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items,Items>>





    | 

    

|===









==== Items [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Downwardapi.Items

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        downwardapi:
          items: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesDownwardAPIItems]

[cols="2,4"]

|===

| Field| Description



    | *fieldRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items_fieldRef,

















FieldRef







>>

        

    

    | 

    

    | *mode* +

    







integer

















    | 

    

    | *path* +

    





string



















    | 

    

    | *resourceFieldRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items_resourceFieldRef,

















ResourceFieldRef







>>

        

    

    | 

    

|===









==== Fieldref [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items_fieldRef]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Downwardapi.Items.Fieldref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        downwardapi:
          items:
            fieldref: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesDownwardAPIItemsFieldRef]

[cols="2,4"]

|===

| Field| Description



    | *apiVersion* +

    





string



















    | 

    

    | *fieldPath* +

    





string



















    | 

    

|===









==== Resourcefieldref [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items_resourceFieldRef]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Downwardapi.Items.Resourcefieldref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        downwardapi:
          items:
            resourcefieldref: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesDownwardAPIItemsResourceFieldRef]

[cols="2,4"]

|===

| Field| Description



    | *containerName* +

    





string



















    | 

    

    | *divisor* +

            

integer or string

























            

        

    

    | 

    

    | *resource* +

    





string



















    | 

    

|===









==== Emptydir [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_emptyDir]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Emptydir

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        emptydir: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEmptyDir]

[cols="2,4"]

|===

| Field| Description



    | *medium* +

    





string



















    | 

    

    | *sizeLimit* +

            

integer or string

























            

        

    

    | 

    

|===









==== Ephemeral [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeral]

[cols="2,4"]

|===

| Field| Description



    | *volumeClaimTemplate* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate,

















VolumeClaimTemplate







>>

        

    

    | 

    

|===









==== Volumeclaimtemplate [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplate]

[cols="2,4"]

|===

| Field| Description



    | *metadata* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_metadata,

















Metadata







>>

        

    

    | 

    

    | *spec* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec,

















Spec







>>

        

    

    | 

    

|===









==== Metadata [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_metadata]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Metadata

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            metadata: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateMetadata]

[cols="2,4"]

|===

| Field| Description



    | *annotations* +

    



















[]key/value





    | 

    

    | *creationTimestamp* +

    





string



















    | 

    

    | *deletionGracePeriodSeconds* +

    







integer

















    | 

    

    | *deletionTimestamp* +

    





string



















    | 

    

    | *finalizers* +

    



















[]

string



    | 

    

    | *generateName* +

    





string



















    | 

    

    | *generation* +

    







integer

















    | 

    

    | *labels* +

    



















[]key/value





    | 

    

    | *managedFields* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_metadata_managedFields,ManagedFields>>





    | 

    

    | *name* +

    





string



















    | 

    

    | *namespace* +

    





string



















    | 

    

    | *ownerReferences* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_metadata_ownerReferences,OwnerReferences>>





    | 

    

    | *resourceVersion* +

    





string



















    | 

    

    | *selfLink* +

    





string



















    | 

    

    | *uid* +

    





string



















    | 

    

|===









==== Managedfields [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_metadata_managedFields]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Metadata.Managedfields

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            metadata:
              managedfields: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateMetadataManagedFields]

[cols="2,4"]

|===

| Field| Description



    | *apiVersion* +

    





string



















    | 

    

    | *fieldsType* +

    





string



















    | 

    

    | *fieldsV1* +

    

























    | 

    

    | *manager* +

    





string



















    | 

    

    | *operation* +

    





string



















    | 

    

    | *subresource* +

    





string



















    | 

    

    | *time* +

    





string



















    | 

    

|===









==== Ownerreferences [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_metadata_ownerReferences]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Metadata.Ownerreferences

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            metadata:
              ownerreferences: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateMetadataOwnerReferences]

[cols="2,4"]

|===

| Field| Description



    | *apiVersion* +

    





string



















    | 

    

    | *blockOwnerDeletion* +

    











boolean













    | 

    

    | *controller* +

    











boolean













    | 

    

    | *kind* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

    | *uid* +

    





string



















    | 

    

|===









==== Spec [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Spec

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            spec: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateSpec]

[cols="2,4"]

|===

| Field| Description



    | *accessModes* +

    



















[]

string



    | 

    

    | *dataSource* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_dataSource,

















DataSource







>>

        

    

    | 

    

    | *dataSourceRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_dataSource,

















DataSourceRef







>>

        

    

    | 

    

    | *resources* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_resources,

















Resources







>>

        

    

    | 

    

    | *selector* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_selector,

















Selector







>>

        

    

    | 

    

    | *storageClassName* +

    





string



















    | 

    

    | *volumeMode* +

    





string



















    | 

    

    | *volumeName* +

    





string



















    | 

    

|===









==== Datasource [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_dataSource]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Spec.Datasource

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            spec:
              datasource: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateSpecDataSource]

[cols="2,4"]

|===

| Field| Description



    | *apiGroup* +

    





string



















    | 

    

    | *kind* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

|===









==== Resources [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_resources]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Spec.Resources

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            spec:
              resources: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateSpecResources]

[cols="2,4"]

|===

| Field| Description



    | *limits* +

    



















[]

integer or string



    | 

    

    | *requests* +

    



















[]

integer or string



    | 

    

|===









==== Selector [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_selector]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Spec.Selector

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            spec:
              selector: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateSpecSelector]

[cols="2,4"]

|===

| Field| Description



    | *matchExpressions* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_selector_matchExpressions,MatchExpressions>>





    | 

    

    | *matchLabels* +

    



















[]key/value





    | 

    

|===









==== Matchexpressions [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_selector_matchExpressions]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Ephemeral.Volumeclaimtemplate.Spec.Selector.Matchexpressions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        ephemeral:
          volumeclaimtemplate:
            spec:
              selector:
                matchexpressions: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesEphemeralVolumeClaimTemplateSpecSelectorMatchExpressions]

[cols="2,4"]

|===

| Field| Description



    | *key* +

    





string



















    | 

    

    | *operator* +

    





string



















    | 

    

    | *values* +

    



















[]

string



    | 

    

|===









==== Fc [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_fc]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Fc

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        fc: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesFc]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *lun* +

    







integer

















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *targetWWNs* +

    



















[]

string



    | 

    

    | *wwids* +

    



















[]

string



    | 

    

|===









==== Flexvolume [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_flexVolume]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Flexvolume

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        flexvolume: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesFlexVolume]

[cols="2,4"]

|===

| Field| Description



    | *driver* +

    





string



















    | 

    

    | *fsType* +

    





string



















    | 

    

    | *options* +

    



















[]key/value





    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

|===









==== Flocker [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_flocker]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Flocker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        flocker: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesFlocker]

[cols="2,4"]

|===

| Field| Description



    | *datasetName* +

    





string



















    | 

    

    | *datasetUUID* +

    





string



















    | 

    

|===









==== Gcepersistentdisk [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_gcePersistentDisk]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Gcepersistentdisk

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        gcepersistentdisk: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesGcePersistentDisk]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *partition* +

    







integer

















    | 

    

    | *pdName* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

|===









==== Gitrepo [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_gitRepo]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Gitrepo

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        gitrepo: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesGitRepo]

[cols="2,4"]

|===

| Field| Description



    | *directory* +

    





string



















    | 

    

    | *repository* +

    





string



















    | 

    

    | *revision* +

    





string



















    | 

    

|===









==== Glusterfs [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_glusterfs]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Glusterfs

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        glusterfs: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesGlusterfs]

[cols="2,4"]

|===

| Field| Description



    | *endpoints* +

    





string



















    | 

    

    | *path* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

|===









==== Hostpath [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_hostPath]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Hostpath

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        hostpath: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesHostPath]

[cols="2,4"]

|===

| Field| Description



    | *path* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

|===









==== Iscsi [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_iscsi]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Iscsi

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        iscsi: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesIscsi]

[cols="2,4"]

|===

| Field| Description



    | *chapAuthDiscovery* +

    











boolean













    | 

    

    | *chapAuthSession* +

    











boolean













    | 

    

    | *fsType* +

    





string



















    | 

    

    | *initiatorName* +

    





string



















    | 

    

    | *iqn* +

    





string



















    | 

    

    | *iscsiInterface* +

    





string



















    | 

    

    | *lun* +

    







integer

















    | 

    

    | *portals* +

    



















[]

string



    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

    | *targetPortal* +

    





string



















    | 

    

|===









==== Nfs [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_nfs]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Nfs

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        nfs: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesNfs]

[cols="2,4"]

|===

| Field| Description



    | *path* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *server* +

    





string



















    | 

    

|===









==== Persistentvolumeclaim [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_persistentVolumeClaim]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Persistentvolumeclaim

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        persistentvolumeclaim: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesPersistentVolumeClaim]

[cols="2,4"]

|===

| Field| Description



    | *claimName* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

|===









==== Photonpersistentdisk [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_photonPersistentDisk]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Photonpersistentdisk

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        photonpersistentdisk: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesPhotonPersistentDisk]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *pdID* +

    





string



















    | 

    

|===









==== Portworxvolume [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_portworxVolume]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Portworxvolume

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        portworxvolume: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesPortworxVolume]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *volumeID* +

    





string



















    | 

    

|===









==== Projected [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Projected

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        projected: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesProjected]

[cols="2,4"]

|===

| Field| Description



    | *defaultMode* +

    







integer

















    | 

    

    | *sources* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources,Sources>>





    | 

    

|===









==== Sources [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Projected.Sources

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        projected:
          sources: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesProjectedSources]

[cols="2,4"]

|===

| Field| Description



    | *configMap* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_configMap,

















ConfigMap







>>

        

    

    | 

    

    | *downwardAPI* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_downwardAPI,

















DownwardAPI







>>

        

    

    | 

    

    | *secret* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_configMap,

















Secret







>>

        

    

    | 

    

    | *serviceAccountToken* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_serviceAccountToken,

















ServiceAccountToken







>>

        

    

    | 

    

|===









==== Configmap [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_configMap]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Projected.Sources.Configmap

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        projected:
          sources:
            configmap: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesProjectedSourcesConfigMap]

[cols="2,4"]

|===

| Field| Description



    | *items* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_configMap_items,Items>>





    | 

    

    | *name* +

    





string



















    | 

    

    | *optional* +

    











boolean













    | 

    

|===









==== Downwardapi [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_downwardAPI]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Projected.Sources.Downwardapi

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        projected:
          sources:
            downwardapi: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesProjectedSourcesDownwardAPI]

[cols="2,4"]

|===

| Field| Description



    | *items* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items,Items>>





    | 

    

|===









==== Serviceaccounttoken [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_projected_sources_serviceAccountToken]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Projected.Sources.Serviceaccounttoken

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        projected:
          sources:
            serviceaccounttoken: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesProjectedSourcesServiceAccountToken]

[cols="2,4"]

|===

| Field| Description



    | *audience* +

    





string



















    | 

    

    | *expirationSeconds* +

    







integer

















    | 

    

    | *path* +

    





string



















    | 

    

|===









==== Quobyte [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_quobyte]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Quobyte

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        quobyte: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesQuobyte]

[cols="2,4"]

|===

| Field| Description



    | *group* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *registry* +

    





string



















    | 

    

    | *tenant* +

    





string



















    | 

    

    | *user* +

    





string



















    | 

    

    | *volume* +

    





string



















    | 

    

|===









==== Rbd [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_rbd]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Rbd

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        rbd: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesRbd]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *image* +

    





string



















    | 

    

    | *keyring* +

    





string



















    | 

    

    | *monitors* +

    



















[]

string



    | 

    

    | *pool* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

    | *user* +

    





string



















    | 

    

|===









==== Scaleio [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_scaleIO]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Scaleio

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        scaleio: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesScaleIO]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *gateway* +

    





string



















    | 

    

    | *protectionDomain* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

    | *sslEnabled* +

    











boolean













    | 

    

    | *storageMode* +

    





string



















    | 

    

    | *storagePool* +

    





string



















    | 

    

    | *system* +

    





string



















    | 

    

    | *volumeName* +

    





string



















    | 

    

|===









==== Secret [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_secret]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Secret

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        secret: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesSecret]

[cols="2,4"]

|===

| Field| Description



    | *defaultMode* +

    







integer

















    | 

    

    | *items* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_configMap_items,Items>>





    | 

    

    | *optional* +

    











boolean













    | 

    

    | *secretName* +

    





string



















    | 

    

|===









==== Storageos [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_storageos]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Storageos

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        storageos: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesStorageos]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *readOnly* +

    











boolean













    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,

















SecretRef







>>

        

    

    | 

    

    | *volumeName* +

    





string



















    | 

    

    | *volumeNamespace* +

    





string



















    | 

    

|===









==== Vspherevolume [[BookKeeper_spec_bookkeeper_additionalVolumes_volumes_vsphereVolume]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Additionalvolumes.Volumes.Vspherevolume

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    additionalvolumes:
      volumes:
        vspherevolume: {}

----


[.fields-BookKeeperSpecBookkeeperAdditionalVolumesVolumesVsphereVolume]

[cols="2,4"]

|===

| Field| Description



    | *fsType* +

    





string



















    | 

    

    | *storagePolicyID* +

    





string



















    | 

    

    | *storagePolicyName* +

    





string



















    | 

    

    | *volumePath* +

    





string



















    | 

    

|===









==== Antiaffinity [[BookKeeper_spec_bookkeeper_antiAffinity]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Antiaffinity

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    antiaffinity: {}

----


[.fields-BookKeeperSpecBookkeeperAntiAffinity]

[cols="2,4"]

|===

| Field| Description



    | *host* +

            

            <<BookKeeper_spec_bookkeeper_antiAffinity_host,

















Host







>>

        

    

    | 

    

    | *zone* +

            

            <<BookKeeper_spec_bookkeeper_antiAffinity_zone,

















Zone







>>

        

    

    | 

    

|===









==== Host [[BookKeeper_spec_bookkeeper_antiAffinity_host]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Antiaffinity.Host

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    antiaffinity:
      host: {}

----


[.fields-BookKeeperSpecBookkeeperAntiAffinityHost]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

    | *required* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

|===









==== Zone [[BookKeeper_spec_bookkeeper_antiAffinity_zone]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Antiaffinity.Zone

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    antiaffinity:
      zone: {}

----


[.fields-BookKeeperSpecBookkeeperAntiAffinityZone]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

    | *required* +

    











boolean













    | 

    Indicates the reclaimPolicy property for the StorageClass.

|===









==== Autorackconfig [[BookKeeper_spec_bookkeeper_autoRackConfig]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Autorackconfig

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    autorackconfig: {}

----


[.fields-BookKeeperSpecBookkeeperAutoRackConfig]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable rack configuration monitoring.

    | *periodMs* +

    







integer

















    | 

    Period for the schedule of the monitoring thread.

|===









==== Autoscaler [[BookKeeper_spec_bookkeeper_autoscaler]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Autoscaler

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    autoscaler: {}

----


[.fields-BookKeeperSpecBookkeeperAutoscaler]

[cols="2,4"]

|===

| Field| Description



    | *diskUsageToleranceHwm* +

    







bigdecimal

















    | 

    The threshold to trigger a scale down. The autoscaler will scale down if all the bookies&#39; disk usage is lower than this threshold. Default is &#39;0.92&#39;

    | *diskUsageToleranceLwm* +

    







bigdecimal

















    | 

    The threshold to trigger a scale up. The autoscaler will scale up if all the bookies&#39; disk usage is higher than this threshold. Default is &#39;0.75&#39;

    | *enabled* +

    











boolean













    | 

    Enable autoscaling for bookies.

    | *minWritableBookies* +

    







integer

















    | 

    Min number of writable bookies. The autoscaler will scale up if not enough writable bookies are detected. For instance, if a bookie went to read-only mode, the autoscaler will scale up to replace it. Default is &#39;3&#39;.

    | *periodMs* +

    







integer

















    | 

    The interval in milliseconds between two consecutive autoscaling checks.

    | *scaleDownBy* +

    







integer

















    | 

    The number of bookies to remove at each scale down. Default is &#39;1&#39;

    | *scaleUpBy* +

    







integer

















    | 

    The number of bookies to add at each scale up. Default is &#39;1&#39;

    | *scaleUpMaxLimit* +

    







integer

















    | 

    Max number of bookies. If the number of bookies is equals to this value, the autoscaler will never scale up.

    | *stabilizationWindowMs* +

    







integer

















    | 

    The stabilization window is used to restrict the flapping of replica count when the metrics used for scaling keep fluctuating. The autoscaling algorithm uses this window to infer a previous desired state and avoid unwanted changes to workload scale.Default value is 5 minutes after the pod readiness.

|===









==== Env [[BookKeeper_spec_bookkeeper_env]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Env

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    env: {}

----


[.fields-BookKeeperSpecBookkeeperEnv]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

    | *value* +

    





string



















    | 

    

    | *valueFrom* +

            

            <<BookKeeper_spec_bookkeeper_env_valueFrom,

















ValueFrom







>>

        

    

    | 

    

|===









==== Valuefrom [[BookKeeper_spec_bookkeeper_env_valueFrom]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Env.Valuefrom

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    env:
      valuefrom: {}

----


[.fields-BookKeeperSpecBookkeeperEnvValueFrom]

[cols="2,4"]

|===

| Field| Description



    | *configMapKeyRef* +

            

            <<BookKeeper_spec_bookkeeper_env_valueFrom_configMapKeyRef,

















ConfigMapKeyRef







>>

        

    

    | 

    

    | *fieldRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items_fieldRef,

















FieldRef







>>

        

    

    | 

    

    | *resourceFieldRef* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_downwardAPI_items_resourceFieldRef,

















ResourceFieldRef







>>

        

    

    | 

    

    | *secretKeyRef* +

            

            <<BookKeeper_spec_bookkeeper_env_valueFrom_configMapKeyRef,

















SecretKeyRef







>>

        

    

    | 

    

|===









==== Configmapkeyref [[BookKeeper_spec_bookkeeper_env_valueFrom_configMapKeyRef]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Env.Valuefrom.Configmapkeyref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    env:
      valuefrom:
        configmapkeyref: {}

----


[.fields-BookKeeperSpecBookkeeperEnvValueFromConfigMapKeyRef]

[cols="2,4"]

|===

| Field| Description



    | *key* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

    | *optional* +

    











boolean













    | 

    

|===









==== Initcontainers [[BookKeeper_spec_bookkeeper_initContainers]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainers]

[cols="2,4"]

|===

| Field| Description



    | *args* +

    



















[]

string



    | 

    

    | *command* +

    



















[]

string



    | 

    

    | *env* +

    



















[]<<BookKeeper_spec_bookkeeper_env,Env>>





    | 

    

    | *envFrom* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers_envFrom,EnvFrom>>





    | 

    

    | *image* +

    





string



















    | 

    

    | *imagePullPolicy* +

    





string



















    | 

    

    | *lifecycle* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle,

















Lifecycle







>>

        

    

    | 

    

    | *livenessProbe* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_livenessProbe,

















LivenessProbe







>>

        

    

    | 

    

    | *name* +

    





string



















    | 

    

    | *ports* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers_ports,Ports>>





    | 

    

    | *readinessProbe* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_livenessProbe,

















ReadinessProbe







>>

        

    

    | 

    

    | *resources* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_resources,

















Resources







>>

        

    

    | 

    

    | *securityContext* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_securityContext,

















SecurityContext







>>

        

    

    | 

    

    | *startupProbe* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_livenessProbe,

















StartupProbe







>>

        

    

    | 

    

    | *stdin* +

    











boolean













    | 

    

    | *stdinOnce* +

    











boolean













    | 

    

    | *terminationMessagePath* +

    





string



















    | 

    

    | *terminationMessagePolicy* +

    





string



















    | 

    

    | *tty* +

    











boolean













    | 

    

    | *volumeDevices* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers_volumeDevices,VolumeDevices>>





    | 

    

    | *volumeMounts* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_mounts,VolumeMounts>>





    | 

    

    | *workingDir* +

    





string



















    | 

    

|===









==== Envfrom [[BookKeeper_spec_bookkeeper_initContainers_envFrom]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Envfrom

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      envfrom: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersEnvFrom]

[cols="2,4"]

|===

| Field| Description



    | *configMapRef* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_envFrom_configMapRef,

















ConfigMapRef







>>

        

    

    | 

    

    | *prefix* +

    





string



















    | 

    

    | *secretRef* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_envFrom_configMapRef,

















SecretRef







>>

        

    

    | 

    

|===









==== Configmapref [[BookKeeper_spec_bookkeeper_initContainers_envFrom_configMapRef]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Envfrom.Configmapref

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      envfrom:
        configmapref: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersEnvFromConfigMapRef]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

    | *optional* +

    











boolean













    | 

    

|===









==== Lifecycle [[BookKeeper_spec_bookkeeper_initContainers_lifecycle]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Lifecycle

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      lifecycle: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLifecycle]

[cols="2,4"]

|===

| Field| Description



    | *postStart* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart,

















PostStart







>>

        

    

    | 

    

    | *preStop* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart,

















PreStop







>>

        

    

    | 

    

|===









==== Poststart [[BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Lifecycle.Poststart

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      lifecycle:
        poststart: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLifecyclePostStart]

[cols="2,4"]

|===

| Field| Description



    | *exec* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_exec,

















Exec







>>

        

    

    | 

    

    | *httpGet* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_httpGet,

















HttpGet







>>

        

    

    | 

    

    | *tcpSocket* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_tcpSocket,

















TcpSocket







>>

        

    

    | 

    

|===









==== Exec [[BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_exec]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Lifecycle.Poststart.Exec

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      lifecycle:
        poststart:
          exec: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLifecyclePostStartExec]

[cols="2,4"]

|===

| Field| Description



    | *command* +

    



















[]

string



    | 

    

|===









==== Httpget [[BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_httpGet]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Lifecycle.Poststart.Httpget

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      lifecycle:
        poststart:
          httpget: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLifecyclePostStartHttpGet]

[cols="2,4"]

|===

| Field| Description



    | *host* +

    





string



















    | 

    

    | *httpHeaders* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_httpGet_httpHeaders,HttpHeaders>>





    | 

    

    | *path* +

    





string



















    | 

    

    | *port* +

            

integer or string

























            

        

    

    | 

    

    | *scheme* +

    





string



















    | 

    

|===









==== Httpheaders [[BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_httpGet_httpHeaders]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Lifecycle.Poststart.Httpget.Httpheaders

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      lifecycle:
        poststart:
          httpget:
            httpheaders: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLifecyclePostStartHttpGetHttpHeaders]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | 

    

    | *value* +

    





string



















    | 

    

|===









==== Tcpsocket [[BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_tcpSocket]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Lifecycle.Poststart.Tcpsocket

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      lifecycle:
        poststart:
          tcpsocket: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLifecyclePostStartTcpSocket]

[cols="2,4"]

|===

| Field| Description



    | *host* +

    





string



















    | 

    

    | *port* +

            

integer or string

























            

        

    

    | 

    

|===









==== Livenessprobe [[BookKeeper_spec_bookkeeper_initContainers_livenessProbe]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Livenessprobe

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      livenessprobe: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLivenessProbe]

[cols="2,4"]

|===

| Field| Description



    | *exec* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_exec,

















Exec







>>

        

    

    | 

    

    | *failureThreshold* +

    







integer

















    | 

    

    | *grpc* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_livenessProbe_grpc,

















Grpc







>>

        

    

    | 

    

    | *httpGet* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_httpGet,

















HttpGet







>>

        

    

    | 

    

    | *initialDelaySeconds* +

    







integer

















    | 

    

    | *periodSeconds* +

    







integer

















    | 

    

    | *successThreshold* +

    







integer

















    | 

    

    | *tcpSocket* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_tcpSocket,

















TcpSocket







>>

        

    

    | 

    

    | *terminationGracePeriodSeconds* +

    







integer

















    | 

    

    | *timeoutSeconds* +

    







integer

















    | 

    

|===









==== Grpc [[BookKeeper_spec_bookkeeper_initContainers_livenessProbe_grpc]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Livenessprobe.Grpc

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      livenessprobe:
        grpc: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersLivenessProbeGrpc]

[cols="2,4"]

|===

| Field| Description



    | *port* +

    







integer

















    | 

    

    | *service* +

    





string



















    | 

    

|===









==== Ports [[BookKeeper_spec_bookkeeper_initContainers_ports]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Ports

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      ports: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersPorts]

[cols="2,4"]

|===

| Field| Description



    | *containerPort* +

    







integer

















    | 

    

    | *hostIP* +

    





string



















    | 

    

    | *hostPort* +

    







integer

















    | 

    

    | *name* +

    





string



















    | 

    

    | *protocol* +

    





string



















    | 

    

|===









==== Securitycontext [[BookKeeper_spec_bookkeeper_initContainers_securityContext]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Securitycontext

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      securitycontext: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersSecurityContext]

[cols="2,4"]

|===

| Field| Description



    | *allowPrivilegeEscalation* +

    











boolean













    | 

    

    | *capabilities* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_securityContext_capabilities,

















Capabilities







>>

        

    

    | 

    

    | *privileged* +

    











boolean













    | 

    

    | *procMount* +

    





string



















    | 

    

    | *readOnlyRootFilesystem* +

    











boolean













    | 

    

    | *runAsGroup* +

    







integer

















    | 

    

    | *runAsNonRoot* +

    











boolean













    | 

    

    | *runAsUser* +

    







integer

















    | 

    

    | *seLinuxOptions* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_securityContext_seLinuxOptions,

















SeLinuxOptions







>>

        

    

    | 

    

    | *seccompProfile* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_securityContext_seccompProfile,

















SeccompProfile







>>

        

    

    | 

    

    | *windowsOptions* +

            

            <<BookKeeper_spec_bookkeeper_initContainers_securityContext_windowsOptions,

















WindowsOptions







>>

        

    

    | 

    

|===









==== Capabilities [[BookKeeper_spec_bookkeeper_initContainers_securityContext_capabilities]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Securitycontext.Capabilities

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      securitycontext:
        capabilities: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersSecurityContextCapabilities]

[cols="2,4"]

|===

| Field| Description



    | *add* +

    



















[]

string



    | 

    

    | *drop* +

    



















[]

string



    | 

    

|===









==== Selinuxoptions [[BookKeeper_spec_bookkeeper_initContainers_securityContext_seLinuxOptions]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Securitycontext.Selinuxoptions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      securitycontext:
        selinuxoptions: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersSecurityContextSeLinuxOptions]

[cols="2,4"]

|===

| Field| Description



    | *level* +

    





string



















    | 

    

    | *role* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

    | *user* +

    





string



















    | 

    

|===









==== Seccompprofile [[BookKeeper_spec_bookkeeper_initContainers_securityContext_seccompProfile]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Securitycontext.Seccompprofile

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      securitycontext:
        seccompprofile: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersSecurityContextSeccompProfile]

[cols="2,4"]

|===

| Field| Description



    | *localhostProfile* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

|===









==== Windowsoptions [[BookKeeper_spec_bookkeeper_initContainers_securityContext_windowsOptions]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Securitycontext.Windowsoptions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      securitycontext:
        windowsoptions: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersSecurityContextWindowsOptions]

[cols="2,4"]

|===

| Field| Description



    | *gmsaCredentialSpec* +

    





string



















    | 

    

    | *gmsaCredentialSpecName* +

    





string



















    | 

    

    | *hostProcess* +

    











boolean













    | 

    

    | *runAsUserName* +

    





string



















    | 

    

|===









==== Volumedevices [[BookKeeper_spec_bookkeeper_initContainers_volumeDevices]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Initcontainers.Volumedevices

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    initcontainers:
      volumedevices: {}

----


[.fields-BookKeeperSpecBookkeeperInitContainersVolumeDevices]

[cols="2,4"]

|===

| Field| Description



    | *devicePath* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

|===









==== Nodeaffinity [[BookKeeper_spec_bookkeeper_nodeAffinity]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Nodeaffinity

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    nodeaffinity: {}

----


[.fields-BookKeeperSpecBookkeeperNodeAffinity]

[cols="2,4"]

|===

| Field| Description



    | *preferredDuringSchedulingIgnoredDuringExecution* +

    



















[]<<BookKeeper_spec_bookkeeper_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution,PreferredDuringSchedulingIgnoredDuringExecution>>





    | 

    

    | *requiredDuringSchedulingIgnoredDuringExecution* +

            

            <<BookKeeper_spec_bookkeeper_nodeAffinity_requiredDuringSchedulingIgnoredDuringExecution,

















RequiredDuringSchedulingIgnoredDuringExecution







>>

        

    

    | 

    

|===









==== Preferredduringschedulingignoredduringexecution [[BookKeeper_spec_bookkeeper_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Nodeaffinity.Preferredduringschedulingignoredduringexecution

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    nodeaffinity:
      preferredduringschedulingignoredduringexecution: {}

----


[.fields-BookKeeperSpecBookkeeperNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution]

[cols="2,4"]

|===

| Field| Description



    | *preference* +

            

            <<BookKeeper_spec_bookkeeper_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference,

















Preference







>>

        

    

    | 

    

    | *weight* +

    







integer

















    | 

    

|===









==== Preference [[BookKeeper_spec_bookkeeper_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Nodeaffinity.Preferredduringschedulingignoredduringexecution.Preference

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    nodeaffinity:
      preferredduringschedulingignoredduringexecution:
        preference: {}

----


[.fields-BookKeeperSpecBookkeeperNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference]

[cols="2,4"]

|===

| Field| Description



    | *matchExpressions* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_selector_matchExpressions,MatchExpressions>>





    | 

    

    | *matchFields* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_ephemeral_volumeClaimTemplate_spec_selector_matchExpressions,MatchFields>>





    | 

    

|===









==== Requiredduringschedulingignoredduringexecution [[BookKeeper_spec_bookkeeper_nodeAffinity_requiredDuringSchedulingIgnoredDuringExecution]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Nodeaffinity.Requiredduringschedulingignoredduringexecution

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    nodeaffinity:
      requiredduringschedulingignoredduringexecution: {}

----


[.fields-BookKeeperSpecBookkeeperNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution]

[cols="2,4"]

|===

| Field| Description



    | *nodeSelectorTerms* +

    



















[]<<BookKeeper_spec_bookkeeper_nodeAffinity_preferredDuringSchedulingIgnoredDuringExecution_preference,NodeSelectorTerms>>





    | 

    

|===









==== Pdb [[BookKeeper_spec_bookkeeper_pdb]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Pdb

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    pdb: {}

----


[.fields-BookKeeperSpecBookkeeperPdb]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable Pdb policy.

    | *maxUnavailable* +

    







integer

















    | 

    Number of maxUnavailable pods.

|===









==== Probes [[BookKeeper_spec_bookkeeper_probes]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Probes

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    probes: {}

----


[.fields-BookKeeperSpecBookkeeperProbes]

[cols="2,4"]

|===

| Field| Description



    | *liveness* +

            

            <<BookKeeper_spec_bookkeeper_probes_liveness,

















Liveness







>>

        

    

    | 

    

    | *readiness* +

            

            <<BookKeeper_spec_bookkeeper_probes_readiness,

















Readiness







>>

        

    

    | 

    

|===









==== Liveness [[BookKeeper_spec_bookkeeper_probes_liveness]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Probes.Liveness

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    probes:
      liveness: {}

----


[.fields-BookKeeperSpecBookkeeperProbesLiveness]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enables the probe.

    | *failureThreshold* +

    







integer

















    | 

    Failure threshold.

    | *initialDelaySeconds* +

    







integer

















    | 

    Indicates the initial delay (in seconds) for the probe.

    | *periodSeconds* +

    







integer

















    | 

    Indicates the period (in seconds) for the probe.

    | *successThreshold* +

    







integer

















    | 

    Success threshold.

    | *terminationGracePeriodSeconds* +

    







integer

















    | 

    Indicates the termination grace period (in seconds) for the probe.

    | *timeoutSeconds* +

    







integer

















    | 

    Indicates the timeout (in seconds) for the probe.

|===









==== Readiness [[BookKeeper_spec_bookkeeper_probes_readiness]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Probes.Readiness

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    probes:
      readiness: {}

----


[.fields-BookKeeperSpecBookkeeperProbesReadiness]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enables the probe.

    | *failureThreshold* +

    







integer

















    | 

    Failure threshold.

    | *initialDelaySeconds* +

    







integer

















    | 

    Indicates the initial delay (in seconds) for the probe.

    | *periodSeconds* +

    







integer

















    | 

    Indicates the period (in seconds) for the probe.

    | *successThreshold* +

    







integer

















    | 

    Success threshold.

    | *terminationGracePeriodSeconds* +

    







integer

















    | 

    Indicates the termination grace period (in seconds) for the probe.

    | *timeoutSeconds* +

    







integer

















    | 

    Indicates the timeout (in seconds) for the probe.

|===









==== Resources [[BookKeeper_spec_bookkeeper_resources]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Resources

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    resources: {}

----


[.fields-BookKeeperSpecBookkeeperResources]

[cols="2,4"]

|===

| Field| Description



    | *limits* +

    



















[]

integer or string



    | 

    

    | *requests* +

    



















[]

integer or string



    | 

    

|===









==== Service [[BookKeeper_spec_bookkeeper_service]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Service

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    service: {}

----


[.fields-BookKeeperSpecBookkeeperService]

[cols="2,4"]

|===

| Field| Description



    | *additionalPorts* +

    



















[]<<BookKeeper_spec_bookkeeper_service_additionalPorts,AdditionalPorts>>





    | 

    Additional ports to add to the Service.

    | *annotations* +

    



















[]key/value





    | 

    Additional annotations to add to the Service.

|===









==== Additionalports [[BookKeeper_spec_bookkeeper_service_additionalPorts]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Service.Additionalports

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    service:
      additionalports: {}

----


[.fields-BookKeeperSpecBookkeeperServiceAdditionalPorts]

[cols="2,4"]

|===

| Field| Description



    | *appProtocol* +

    





string



















    | 

    

    | *name* +

    





string



















    | 

    

    | *nodePort* +

    







integer

















    | 

    

    | *port* +

    







integer

















    | 

    

    | *protocol* +

    





string



















    | 

    

    | *targetPort* +

            

integer or string

























            

        

    

    | 

    

|===









==== Sets [[BookKeeper_spec_bookkeeper_sets]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets: {}

----


[.fields-BookKeeperSpecBookkeeperSets]

[cols="2,4"]

|===

| Field| Description



    | *additionalVolumes* +

            

            <<BookKeeper_spec_bookkeeper_additionalVolumes,

















AdditionalVolumes







>>

        

    

    | 

    

    | *annotations* +

    



















[]key/value





    | 

    Annotations to add to each resource (except pods).

    | *antiAffinity* +

            

            <<BookKeeper_spec_bookkeeper_antiAffinity,

















AntiAffinity







>>

        

    

    | 

    

    | *autoscaler* +

            

            <<BookKeeper_spec_bookkeeper_autoscaler,

















Autoscaler







>>

        

    

    | 

    

    | *cleanUpPvcs* +

    











boolean













    | 

    Cleanup PVCs after the bookie has been removed.

    | *config* +

    



















any





    | 

    Configuration.

    | *env* +

    



















[]<<BookKeeper_spec_bookkeeper_env,Env>>





    | 

    Additional container env variables.

    | *gracePeriod* +

    







integer

















    | 

    Termination grace period in seconds.

    | *image* +

    





string



















    | 

    Override Pulsar image.

    | *imagePullPolicy* +

    





string



















    | 

    Override image pull policy.

    | *imagePullSecrets* +

    



















[]<<BookKeeper_spec_bookkeeper_additionalVolumes_volumes_cephfs_secretRef,ImagePullSecrets>>





    | 

    Image pull secrets.

    | *initContainers* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers,InitContainers>>





    | 

    Init containers

    | *labels* +

    



















[]key/value





    | 

    Labels to add to each resource (except pods).

    | *matchLabels* +

    



















[]key/value





    | 

    Match labels selectors to add to each pod.

    | *nodeAffinity* +

            

            <<BookKeeper_spec_bookkeeper_nodeAffinity,

















NodeAffinity







>>

        

    

    | 

    

    | *nodeSelectors* +

    



















[]key/value





    | 

    Additional node selectors.

    | *overrideResourceName* +

    





string



















    | 

    Override the resource names generated by the operator.

    | *pdb* +

            

            <<BookKeeper_spec_bookkeeper_pdb,

















Pdb







>>

        

    

    | 

    

    | *podAnnotations* +

    



















[]key/value





    | 

    Annotations to add to pod.

    | *podLabels* +

    



















[]key/value





    | 

    Labels to add to each pod.

    | *podManagementPolicy* +

    





string



















    | 

    Pod management policy. Default value is &#39;Parallel&#39;.

    | *probes* +

            

            <<BookKeeper_spec_bookkeeper_probes,

















Probes







>>

        

    

    | 

    

    | *pvcPrefix* +

    





string



















    | 

    Prefix for each PVC created.

    | *replicas* +

    







integer

















    | 

    Number of desired replicas.

    | *resources* +

            

            <<BookKeeper_spec_bookkeeper_resources,

















Resources







>>

        

    

    | 

    

    | *service* +

            

            <<BookKeeper_spec_bookkeeper_service,

















Service







>>

        

    

    | 

    

    | *sidecars* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers,Sidecars>>





    | 

    Sidecar containers

    | *tolerations* +

    



















[]<<BookKeeper_spec_bookkeeper_sets_tolerations,Tolerations>>





    | 

    Pod tolerations.

    | *updateStrategy* +

            

            <<BookKeeper_spec_bookkeeper_sets_updateStrategy,

















UpdateStrategy







>>

        

    

    | 

    

    | *volumes* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes,

















Volumes







>>

        

    

    | 

    

|===









==== Tolerations [[BookKeeper_spec_bookkeeper_sets_tolerations]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Tolerations

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      tolerations: {}

----


[.fields-BookKeeperSpecBookkeeperSetsTolerations]

[cols="2,4"]

|===

| Field| Description



    | *effect* +

    





string



















    | 

    

    | *key* +

    





string



















    | 

    

    | *operator* +

    





string



















    | 

    

    | *tolerationSeconds* +

    







integer

















    | 

    

    | *value* +

    





string



















    | 

    

|===









==== Updatestrategy [[BookKeeper_spec_bookkeeper_sets_updateStrategy]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Updatestrategy

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      updatestrategy: {}

----


[.fields-BookKeeperSpecBookkeeperSetsUpdateStrategy]

[cols="2,4"]

|===

| Field| Description



    | *rollingUpdate* +

            

            <<BookKeeper_spec_bookkeeper_sets_updateStrategy_rollingUpdate,

















RollingUpdate







>>

        

    

    | 

    

    | *type* +

    





string



















    | 

    

|===









==== Rollingupdate [[BookKeeper_spec_bookkeeper_sets_updateStrategy_rollingUpdate]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Updatestrategy.Rollingupdate

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      updatestrategy:
        rollingupdate: {}

----


[.fields-BookKeeperSpecBookkeeperSetsUpdateStrategyRollingUpdate]

[cols="2,4"]

|===

| Field| Description



    | *maxUnavailable* +

            

integer or string

























            

        

    

    | 

    

    | *partition* +

    







integer

















    | 

    

|===









==== Volumes [[BookKeeper_spec_bookkeeper_sets_volumes]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Volumes

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      volumes: {}

----


[.fields-BookKeeperSpecBookkeeperSetsVolumes]

[cols="2,4"]

|===

| Field| Description



    | *journal* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes_journal,

















Journal







>>

        

    

    | 

    

    | *ledgers* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes_ledgers,

















Ledgers







>>

        

    

    | 

    

|===









==== Journal [[BookKeeper_spec_bookkeeper_sets_volumes_journal]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Volumes.Journal

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      volumes:
        journal: {}

----


[.fields-BookKeeperSpecBookkeeperSetsVolumesJournal]

[cols="2,4"]

|===

| Field| Description



    | *existingStorageClassName* +

    





string



















    | 

    Indicates if an already existing storage class should be used.

    | *name* +

    





string



















    | 

    Indicates the suffix for the volume. Default value is &#39;data&#39;.

    | *size* +

    





string



















    | 

    Indicates the requested size for the volume. The format follows the Kubernetes&#39; Quantity.

    | *storageClass* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes_journal_storageClass,

















StorageClass







>>

        

    

    | 

    

|===









==== Storageclass [[BookKeeper_spec_bookkeeper_sets_volumes_journal_storageClass]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Volumes.Journal.Storageclass

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      volumes:
        journal:
          storageclass: {}

----


[.fields-BookKeeperSpecBookkeeperSetsVolumesJournalStorageClass]

[cols="2,4"]

|===

| Field| Description



    | *extraParams* +

    



















[]key/value





    | 

    Adds extra parameters for the StorageClass.

    | *fsType* +

    





string



















    | 

    Indicates the &#39;fsType&#39; parameter for the StorageClass.

    | *provisioner* +

    





string



















    | 

    Indicates the provisioner property for the StorageClass.

    | *reclaimPolicy* +

    





string



















    | 

    Indicates the reclaimPolicy property for the StorageClass.

    | *type* +

    





string



















    | 

    Indicates the &#39;type&#39; parameter for the StorageClass.

|===









==== Ledgers [[BookKeeper_spec_bookkeeper_sets_volumes_ledgers]]

Complete namespace: Bookkeeper.Spec.Bookkeeper.Sets.Volumes.Ledgers

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  bookkeeper:
    sets:
      volumes:
        ledgers: {}

----


[.fields-BookKeeperSpecBookkeeperSetsVolumesLedgers]

[cols="2,4"]

|===

| Field| Description



    | *existingStorageClassName* +

    





string



















    | 

    Indicates if an already existing storage class should be used.

    | *name* +

    





string



















    | 

    Indicates the suffix for the volume. Default value is &#39;data&#39;.

    | *size* +

    





string



















    | 

    Indicates the requested size for the volume. The format follows the Kubernetes&#39; Quantity.

    | *storageClass* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes_journal_storageClass,

















StorageClass







>>

        

    

    | 

    

|===









==== Global [[BookKeeper_spec_global]]

Complete namespace: Bookkeeper.Spec.Global

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global: {}

----


[.fields-BookKeeperSpecGlobal]

[cols="2,4"]

|===

| Field| Description



    | *name* +

    





string



















    | _(Optional)_ + 

    Pulsar cluster name.

    | *antiAffinity* +

            

            <<BookKeeper_spec_global_antiAffinity,

















AntiAffinity







>>

        

    

    | 

    

    | *auth* +

            

            <<BookKeeper_spec_global_auth,

















Auth







>>

        

    

    | 

    

    | *components* +

            

            <<BookKeeper_spec_global_components,

















Components







>>

        

    

    | 

    

    | *dnsConfig* +

            

            <<BookKeeper_spec_global_dnsConfig,

















DnsConfig







>>

        

    

    | 

    

    | *dnsName* +

    





string



















    | 

    Public dns name for the cluster&#39;s load balancer.

    | *image* +

    





string



















    | 

    Default Pulsar image to use. Any components can be configured to use a different image.

    | *imagePullPolicy* +

    





string



















    | 

    Default Pulsar image pull policy to use. Any components can be configured to use a different image pull policy. Default value is &#39;IfNotPresent&#39;.

    | *kubernetesClusterDomain* +

    





string



















    | 

    The domain name for your kubernetes cluster. This domain is documented here: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records-1 . It&#39;s used to fully qualify service names when configuring Pulsar. The default value is &#39;cluster.local&#39;. 

    | *nodeSelectors* +

    



















[]key/value





    | 

    Global node selector. If set, this will apply to all the components.

    | *persistence* +

    











boolean













    | 

    If persistence is enabled, components that has state will be deployed with PersistentVolumeClaims, otherwise, for test purposes, they will be deployed with emptyDir 

    | *priorityClassName* +

    





string



















    | 

    Priority class name to attach to each pod.

    | *racks* +

    



















[]





    | 

    Racks configuration.

    | *resourceSets* +

    



















[]





    | 

    Resource sets.

    | *restartOnConfigMapChange* +

    











boolean













    | 

    By default, Kubernetes will not restart pods when only their configmap is changed. This setting will restart pods when their configmap is changed using an annotation that calculates the checksum of the configmap. 

    | *storage* +

            

            <<BookKeeper_spec_global_storage,

















Storage







>>

        

    

    | 

    

    | *tls* +

            

            <<BookKeeper_spec_global_tls,

















Tls







>>

        

    

    | 

    

    | *zookeeperPlainSslStorePassword* +

    











boolean













    | 

    Use plain password in zookeeper server and client configuration. Default is false. Old versions of Apache Zookeeper (&lt;3.8.0) does not support getting password from file. In that case, set this to true.

|===









==== Antiaffinity [[BookKeeper_spec_global_antiAffinity]]

Complete namespace: Bookkeeper.Spec.Global.Antiaffinity

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    antiaffinity: {}

----


[.fields-BookKeeperSpecGlobalAntiAffinity]

[cols="2,4"]

|===

| Field| Description



    | *host* +

            

            <<BookKeeper_spec_bookkeeper_antiAffinity_host,

















Host







>>

        

    

    | 

    

    | *zone* +

            

            <<BookKeeper_spec_bookkeeper_antiAffinity_zone,

















Zone







>>

        

    

    | 

    

|===









==== Auth [[BookKeeper_spec_global_auth]]

Complete namespace: Bookkeeper.Spec.Global.Auth

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    auth: {}

----


[.fields-BookKeeperSpecGlobalAuth]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable authentication in the cluster. Default is &#39;false&#39;.

    | *token* +

            

            <<BookKeeper_spec_global_auth_token,

















Token







>>

        

    

    | 

    

|===









==== Token [[BookKeeper_spec_global_auth_token]]

Complete namespace: Bookkeeper.Spec.Global.Auth.Token

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    auth:
      token: {}

----


[.fields-BookKeeperSpecGlobalAuthToken]

[cols="2,4"]

|===

| Field| Description



    | *initialize* +

    











boolean













    | 

    Initialize Secrets with new pair of keys and tokens for the super user roles. The generated Secret name is &#39;token-&lt;role&gt;&#39;.

    | *privateKeyFile* +

    





string



















    | 

    Private key file name stored in the Secret. Default is &#39;my-private.key&#39;

    | *proxyRoles* +

    



















[]

string



    | 

    Proxy roles.

    | *publicKeyFile* +

    





string



















    | 

    Public key file name stored in the Secret. Default is &#39;my-public.key&#39;

    | *superUserRoles* +

    



















[]

string



    | 

    Super user roles.

|===









==== Components [[BookKeeper_spec_global_components]]

Complete namespace: Bookkeeper.Spec.Global.Components

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    components: {}

----


[.fields-BookKeeperSpecGlobalComponents]

[cols="2,4"]

|===

| Field| Description



    | *autorecoveryBaseName* +

    





string



















    | 

    Autorecovery base name. Default value is &#39;autorecovery&#39;.

    | *bastionBaseName* +

    





string



















    | 

    Bastion base name. Default value is &#39;bastion&#39;.

    | *bookkeeperBaseName* +

    





string



















    | 

    BookKeeper base name. Default value is &#39;bookkeeper&#39;.

    | *brokerBaseName* +

    





string



















    | 

    Broker base name. Default value is &#39;broker&#39;.

    | *functionsWorkerBaseName* +

    





string



















    | 

    Functions Worker base name. Default value is &#39;function&#39;.

    | *proxyBaseName* +

    





string



















    | 

    Proxy base name. Default value is &#39;proxy&#39;.

    | *zookeeperBaseName* +

    





string



















    | 

    Zookeeper base name. Default value is &#39;zookeeper&#39;.

|===









==== Dnsconfig [[BookKeeper_spec_global_dnsConfig]]

Complete namespace: Bookkeeper.Spec.Global.Dnsconfig

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    dnsconfig: {}

----


[.fields-BookKeeperSpecGlobalDnsConfig]

[cols="2,4"]

|===

| Field| Description



    | *nameservers* +

    



















[]

string



    | 

    

    | *options* +

    



















[]<<BookKeeper_spec_bookkeeper_initContainers_lifecycle_postStart_httpGet_httpHeaders,Options>>





    | 

    

    | *searches* +

    



















[]

string



    | 

    

|===









==== Racks [[BookKeeper_spec_global_racks]]

Complete namespace: Bookkeeper.Spec.Global.Racks

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    racks: {}

----


[.fields-BookKeeperSpecGlobalRacks]

[cols="2,4"]

|===

| Field| Description



    | *host* +

            

            <<BookKeeper_spec_global_racks_host,

















Host







>>

        

    

    | 

    

    | *zone* +

            

            <<BookKeeper_spec_global_racks_zone,

















Zone







>>

        

    

    | 

    

|===









==== Host [[BookKeeper_spec_global_racks_host]]

Complete namespace: Bookkeeper.Spec.Global.Racks.Host

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    racks:
      host: {}

----


[.fields-BookKeeperSpecGlobalRacksHost]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable the rack affinity rules.

    | *requireRackAffinity* +

    











boolean













    | 

    Indicates if the podAffinity rules will be enforced. Default is false. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

    | *requireRackAntiAffinity* +

    











boolean













    | 

    Indicates if the podAntiAffinity rules will be enforced. Default is true. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

|===









==== Zone [[BookKeeper_spec_global_racks_zone]]

Complete namespace: Bookkeeper.Spec.Global.Racks.Zone

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    racks:
      zone: {}

----


[.fields-BookKeeperSpecGlobalRacksZone]

[cols="2,4"]

|===

| Field| Description



    | *enableHostAntiAffinity* +

    











boolean













    | 

    Enable the host anti affinity. If set, all the pods of the same rack will deployed on different nodes of the same zone.Default is true.

    | *enabled* +

    











boolean













    | 

    Enable the rack affinity rules.

    | *requireRackAffinity* +

    











boolean













    | 

    Indicates if the podAffinity rules will be enforced. Default is false. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

    | *requireRackAntiAffinity* +

    











boolean













    | 

    Indicates if the podAntiAffinity rules will be enforced. Default is true. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

    | *requireRackHostAntiAffinity* +

    











boolean













    | 

    Indicates if the podAntiAffinity rules will be enforced for the host. Default is true. If required, the affinity rule will be enforced using &#39;requiredDuringSchedulingIgnoredDuringExecution&#39;.

|===









==== Resourcesets [[BookKeeper_spec_global_resourceSets]]

Complete namespace: Bookkeeper.Spec.Global.Resourcesets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    resourcesets: {}

----


[.fields-BookKeeperSpecGlobalResourceSets]

[cols="2,4"]

|===

| Field| Description



    | *rack* +

    





string



















    | 

    Place this resource set to a specific rack, defined at .global.racks.

|===









==== Storage [[BookKeeper_spec_global_storage]]

Complete namespace: Bookkeeper.Spec.Global.Storage

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    storage: {}

----


[.fields-BookKeeperSpecGlobalStorage]

[cols="2,4"]

|===

| Field| Description



    | *existingStorageClassName* +

    





string



















    | 

    Indicates if an already existing storage class should be used.

    | *storageClass* +

            

            <<BookKeeper_spec_bookkeeper_sets_volumes_journal_storageClass,

















StorageClass







>>

        

    

    | 

    

|===









==== Tls [[BookKeeper_spec_global_tls]]

Complete namespace: Bookkeeper.Spec.Global.Tls

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls: {}

----


[.fields-BookKeeperSpecGlobalTls]

[cols="2,4"]

|===

| Field| Description



    | *autorecovery* +

            

            <<BookKeeper_spec_global_tls_autorecovery,

















Autorecovery







>>

        

    

    | 

    

    | *bookkeeper* +

            

            <<BookKeeper_spec_global_tls_bookkeeper,

















Bookkeeper







>>

        

    

    | 

    

    | *broker* +

            

            <<BookKeeper_spec_global_tls_broker,

















Broker







>>

        

    

    | 

    

    | *brokerResourceSets* +

    



















[]





    | 

    TLS configurations related to the Broker resource sets.

    | *caPath* +

    





string



















    | 

    Path in the container filesystem where the TLS CA certificates are retrieved. It has to point to a certificate file. The default value is /etc/ssl/certs/ca-certificates.crt.

    | *certProvisioner* +

            

            <<BookKeeper_spec_global_tls_certProvisioner,

















CertProvisioner







>>

        

    

    | 

    

    | *defaultSecretName* +

    





string



















    | 

    Secret name used by each component to load TLS certificates. Each component can load a different secret by setting the &#39;secretName&#39; entry in the tls component spec.

    | *enabled* +

    











boolean













    | 

    Global switch to turn on or off the TLS configurations. Additionally, you have configure each component section.

    | *functionsWorker* +

            

            <<BookKeeper_spec_global_tls_functionsWorker,

















FunctionsWorker







>>

        

    

    | 

    

    | *proxy* +

            

            <<BookKeeper_spec_global_tls_proxy,

















Proxy







>>

        

    

    | 

    

    | *proxyResourceSets* +

    



















[]





    | 

    TLS configurations related to the Proxy resource sets.

    | *ssCa* +

            

            <<BookKeeper_spec_global_tls_ssCa,

















SsCa







>>

        

    

    | 

    

    | *zookeeper* +

            

            <<BookKeeper_spec_global_tls_zookeeper,

















Zookeeper







>>

        

    

    | 

    

|===









==== Autorecovery [[BookKeeper_spec_global_tls_autorecovery]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Autorecovery

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      autorecovery: {}

----


[.fields-BookKeeperSpecGlobalTlsAutorecovery]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Bookkeeper [[BookKeeper_spec_global_tls_bookkeeper]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Bookkeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      bookkeeper: {}

----


[.fields-BookKeeperSpecGlobalTlsBookkeeper]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Broker [[BookKeeper_spec_global_tls_broker]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Broker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      broker: {}

----


[.fields-BookKeeperSpecGlobalTlsBroker]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Brokerresourcesets [[BookKeeper_spec_global_tls_brokerResourceSets]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Brokerresourcesets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      brokerresourcesets: {}

----


[.fields-BookKeeperSpecGlobalTlsBrokerResourceSets]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Certprovisioner [[BookKeeper_spec_global_tls_certProvisioner]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisioner]

[cols="2,4"]

|===

| Field| Description



    | *selfSigned* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned,

















SelfSigned







>>

        

    

    | 

    

|===









==== Selfsigned [[BookKeeper_spec_global_tls_certProvisioner_selfSigned]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSigned]

[cols="2,4"]

|===

| Field| Description



    | *autorecovery* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery,

















Autorecovery







>>

        

    

    | 

    

    | *bookkeeper* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_bookkeeper,

















Bookkeeper







>>

        

    

    | 

    

    | *broker* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_broker,

















Broker







>>

        

    

    | 

    

    | *caSecretName* +

    





string



















    | 

    Secret where to store the root CA certificate.

    | *enabled* +

    











boolean













    | 

    Generate self signed certificates for broker, proxy and functions worker.

    | *functionsWorker* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_functionsWorker,

















FunctionsWorker







>>

        

    

    | 

    

    | *includeDns* +

    











boolean













    | 

    Include dns name in the DNS names covered by the certificate.

    | *perComponent* +

    











boolean













    | 

    Generate a different certificate for each component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

    | *proxy* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_proxy,

















Proxy







>>

        

    

    | 

    

    | *zookeeper* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_zookeeper,

















Zookeeper







>>

        

    

    | 

    

|===









==== Autorecovery [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Autorecovery

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          autorecovery: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedAutorecovery]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Privatekey [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Autorecovery.Privatekey

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          autorecovery:
            privatekey: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedAutorecoveryPrivateKey]

[cols="2,4"]

|===

| Field| Description



    | *algorithm* +

    





string



















    | 

    

    | *encoding* +

    





string



















    | 

    

    | *rotationPolicy* +

    





string



















    | 

    

    | *size* +

    







integer

















    | 

    

|===









==== Bookkeeper [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_bookkeeper]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Bookkeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          bookkeeper: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedBookkeeper]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Broker [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_broker]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Broker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          broker: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedBroker]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Functionsworker [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_functionsWorker]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Functionsworker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          functionsworker: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedFunctionsWorker]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Proxy [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_proxy]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Proxy

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          proxy: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedProxy]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Zookeeper [[BookKeeper_spec_global_tls_certProvisioner_selfSigned_zookeeper]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Certprovisioner.Selfsigned.Zookeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      certprovisioner:
        selfsigned:
          zookeeper: {}

----


[.fields-BookKeeperSpecGlobalTlsCertProvisionerSelfSignedZookeeper]

[cols="2,4"]

|===

| Field| Description



    | *generate* +

    











boolean













    | 

    Generate self signed certificates for the component.

    | *privateKey* +

            

            <<BookKeeper_spec_global_tls_certProvisioner_selfSigned_autorecovery_privateKey,

















PrivateKey







>>

        

    

    | 

    

|===









==== Functionsworker [[BookKeeper_spec_global_tls_functionsWorker]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Functionsworker

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      functionsworker: {}

----


[.fields-BookKeeperSpecGlobalTlsFunctionsWorker]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *enabledWithBroker* +

    











boolean













    | 

    Enable TLS for the functions worker to broker connections.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Proxy [[BookKeeper_spec_global_tls_proxy]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Proxy

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      proxy: {}

----


[.fields-BookKeeperSpecGlobalTlsProxy]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *enabledWithBroker* +

    











boolean













    | 

    Enable TLS for the proxy to broker connections.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Proxyresourcesets [[BookKeeper_spec_global_tls_proxyResourceSets]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Proxyresourcesets

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      proxyresourcesets: {}

----


[.fields-BookKeeperSpecGlobalTlsProxyResourceSets]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *enabledWithBroker* +

    











boolean













    | 

    Enable TLS for the proxy to broker connections.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Ssca [[BookKeeper_spec_global_tls_ssCa]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Ssca

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      ssca: {}

----


[.fields-BookKeeperSpecGlobalTlsSsCa]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









==== Zookeeper [[BookKeeper_spec_global_tls_zookeeper]]

Complete namespace: Bookkeeper.Spec.Global.Tls.Zookeeper

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  global:
    tls:
      zookeeper: {}

----


[.fields-BookKeeperSpecGlobalTlsZookeeper]

[cols="2,4"]

|===

| Field| Description



    | *enabled* +

    











boolean













    | 

    Enable TLS.

    | *secretName* +

    





string



















    | 

    Override the default secret name from where to load the certificates.

|===









=== Status [[BookKeeper_status]]

Complete namespace: Bookkeeper.Status



[.fields-BookKeeperStatus]

[cols="2,4"]

|===

| Field| Description



    | *conditions* +

    



















[]<<BookKeeper_status_conditions,Conditions>>





    | 

    Conditions:  1. Condition Ready: possible status are True or False. If False, the reason contains the error message.

    | *lastApplied* +

    





string



















    | 

    Last spec applied.

|===









==== Conditions [[BookKeeper_status_conditions]]

Complete namespace: Bookkeeper.Status.Conditions

Example use:

[source,yaml]
----
apiVersion: pulsar.oss.datastax.com/v1alpha1
kind: Bookkeeper
metadata:
  name: example-pulsarcluster
spec:
  conditions: {}

----


[.fields-BookKeeperStatusConditions]

[cols="2,4"]

|===

| Field| Description



    | *lastTransitionTime* +

    





string



















    | 

    

    | *message* +

    





string



















    | 

    

    | *observedGeneration* +

    







integer

















    | 

    

    | *reason* +

    





string



















    | 

    

    | *status* +

    





string



















    | 

    

    | *type* +

    





string



















    | 

    

|===

