= Install {pulsar-operator} Helm chart

// Operator Hub
// The install will be updated when chart is available publicly

{pulsar-operator} is installed using Helm.
You can install <<operator,(1)>> just the operator and the PulsarCluster CRDs, or you can install <<values,(2)>> the operator, CRDs, and a Pulsar cluster defined with a values.yaml file.
[#operator]
== Install {pulsar-operator}

Install the DataStax Helm repository:
[source,helm]
----
helm repo add datastax-pulsar https://datastax.github.io/pulsar-helm-chart
helm repo update
----
[TIP]
====
//Learn more about installing the Luna Streaming Helm chart xref:install-upgrade:quickstart-helm-installs.adoc[here].
====

. The {pulsar-operator} Helm chart is currently only available privately.
Download it here: https://github.com/riptano/pulsar-operator/releases/download/pulsar-operator-0.0.4/pulsar-operator-0.0.4.tgz
. Install the {pulsar-operator} Helm chart:
+
[source,helm]
----
helm install pulsar-operator pulsar-operator-0.0.4.tgz
...
NAME: pulsar-operator
LAST DEPLOYED: Wed Mar 15 12:22:29 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
. Ensure pulsar-operator is up and running:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl get deployment
----
--

Result::
+
--
[source,bash]
----
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
pulsar-operator   1/1     1            1           13m
----
--
====
. Describe the deployment:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl describe deployment pulsar-operator
----
--

Result::
+
--
[source,plain]
----
Name:                   pulsar-operator
Namespace:              pulsar-operator
CreationTimestamp:      Tue, 28 Mar 2023 22:14:35 -0400
Labels:                 app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=pulsar-operator
                        app.kubernetes.io/version=
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: pulsar-operator
                        meta.helm.sh/release-namespace: pulsar-cluster
                        prometheus.io/path: /q/metrics
                        prometheus.io/port: 8080
                        prometheus.io/scheme: http
                        prometheus.io/scrape: true
Selector:               app.kubernetes.io/name=pulsar-operator,app.kubernetes.io/version=
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/name=pulsar-operator
                    app.kubernetes.io/version=
  Annotations:      prometheus.io/path: /q/metrics
                    prometheus.io/port: 8080
                    prometheus.io/scheme: http
                    prometheus.io/scrape: true
  Service Account:  pulsar-operator
  Containers:
   pulsar-operator:
    Image:      datastax/lunastreaming-operator:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:8080/q/health/live delay=0s timeout=10s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/q/health/ready delay=0s timeout=10s period=30s #success=1 #failure=3
    Environment:
      KUBERNETES_NAMESPACE:   (v1:metadata.namespace)
    Mounts:                  <none>
  Volumes:                   <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   pulsar-operator-7975c847d4 (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  5m48s  deployment-controller  Scaled up replica set pulsar-operator-7975c847d4 to 1
----
--
====

. You've now installed {pulsar-operator}.
+
By default, when {pulsar-operator} is installed, the PulsarCluster CRDs are also created.
This setting is defined in the {pulsar-operator} values.yaml file as `crd: create: true`.
+
. To see the available CRDs:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl get crds | grep datastax
----
--

Result::
+
--
[source,console]
----
autorecoveries.pulsar.oss.datastax.com           2023-05-12T16:35:59Z
bastions.pulsar.oss.datastax.com                 2023-05-12T16:36:00Z
bookkeepers.pulsar.oss.datastax.com              2023-05-12T16:36:00Z
brokers.pulsar.oss.datastax.com                  2023-05-12T16:36:01Z
functionsworkers.pulsar.oss.datastax.com         2023-05-12T16:36:01Z
proxies.pulsar.oss.datastax.com                  2023-05-12T16:36:02Z
pulsarclusters.pulsar.oss.datastax.com           2023-05-12T16:36:04Z
zookeepers.pulsar.oss.datastax.com               2023-05-12T16:36:06Z
----
--
====

[#values]
== Install {pulsar-operator} Helm chart and a values.yaml file

You can install the {pulsar-operator} with a pre-configured values.yaml file.
This values file configures additional components, such as Broker, Zookeeper, and Bookkeeper pods for your Pulsar cluster.
This is a great way to get a cluster up and running quickly, while still having fine-grained control of each component.

. For this example, we'll install the Pulsar Operator *and* a complete Pulsar cluster with auto-scaling capabilities.
+
[tabs]
====
Helm::
+
--
[source,helm]
----
helm install pulsar helm/pulsar-operator -f helm/examples/bookie-autoscaling/values.yaml
----
--

Result::
+
--
[source,console]
----
NAME: pulsar
LAST DEPLOYED: Fri May 12 12:36:13 2023
NAMESPACE: pulsar-cluster
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
--
====

. To see the available CRDs:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl get crds | grep datastax
----
--

Result::
+
--
[source,console]
----
autorecoveries.pulsar.oss.datastax.com           2023-05-12T16:35:59Z
bastions.pulsar.oss.datastax.com                 2023-05-12T16:36:00Z
bookkeepers.pulsar.oss.datastax.com              2023-05-12T16:36:00Z
brokers.pulsar.oss.datastax.com                  2023-05-12T16:36:01Z
functionsworkers.pulsar.oss.datastax.com         2023-05-12T16:36:01Z
proxies.pulsar.oss.datastax.com                  2023-05-12T16:36:02Z
pulsarclusters.pulsar.oss.datastax.com           2023-05-12T16:36:04Z
zookeepers.pulsar.oss.datastax.com               2023-05-12T16:36:06Z
----
--
====

. To see your new Pulsar cluster up and running:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl get pods -A
----
--

Result::
+
--
[source,console]
----
pulsar-cluster   pulsar-autorecovery-57cfc8b84d-xvchb                       1/1     Running     0          53m
pulsar-cluster   pulsar-bastion-74777cbbf9-pcq5x                            1/1     Running     0          53m
pulsar-cluster   pulsar-bookkeeper-0                                        1/1     Running     0          55m
pulsar-cluster   pulsar-broker-0                                            1/1     Running     0          53m
pulsar-cluster   pulsar-operator-7d8cc69df5-ncs5j                           1/1     Running     0          66m
pulsar-cluster   pulsar-proxy-5bd5cc4fb6-9pnl7                              1/1     Running     0          53m
pulsar-cluster   pulsar-zookeeper-0                                         1/1     Running     0          58m
pulsar-cluster   pulsar-zookeeper-metadata-zgfn4                            0/1     Completed   0          56m
----
--
====

You did it!
You now have a Pulsar cluster up and running with auto-scaling capabilities managed by {pulsar-operator}.

== Uninstall

To uninstall the operator:
[tabs]
====
Helm::
+
--
[source,helm]
----
helm delete pulsar-operator
----
--

Result::
+
--
[source,console]
----
release "pulsar-operator" uninstalled
----
--
====

== What's next?

With your new operator and PulsarCluster resources, you can automate some amazing things.
* xref:
* xref:
* xref: