= Install {pulsar-operator} Helm chart

// Operator Hub
// The install will be updated when chart is available publicly

{pulsar-operator} is installed using Helm.
You can install just the operator and the PulsarCluster CRDs, or you can install xref:stack.adoc[Kaap Stack], which includes the operator, CRDs, and the Prometheus monitoring stack.

[#operator]
== Install {pulsar-operator}
Install the DataStax Helm repository:
[source,helm]
----
helm repo add kaap https://datastax.github.io/kaap
helm repo update
----

. The KAAP Operator Helm chart is available for download (https://github.com/datastax/kaap/releases/latest)[here].
. Install the KAAP operator Helm chart:
+
[source,helm]
----
helm install kaap kaap/kaap
...
NAME: kaap
LAST DEPLOYED: Wed Jun 28 11:37:45 2023
NAMESPACE: pulsar-cluster
STATUS: deployed
REVISION: 1
TEST SUITE: None
----
. Ensure KAAP operator is up and running:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl get deployment
----
--

Result::
+
--
[source,bash]
----
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
kaap   1/1     1            1           13m
----
--
====
. Describe the deployment:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl describe deployment kaap
----
--

Result::
+
--
[source,plain]
----
Name:                   kaap
Namespace:              pulsar-cluster
CreationTimestamp:      Wed, 28 Jun 2023 11:37:49 -0400
Labels:                 app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kaap
                        helm.sh/chart=kaap-0.1.0
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: kaap
                        meta.helm.sh/release-namespace: pulsar-cluster
                        prometheus.io/path: /q/metrics
                        prometheus.io/port: 8080
                        prometheus.io/scheme: http
                        prometheus.io/scrape: true
Selector:               app.kubernetes.io/name=kaap
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/name=kaap
  Annotations:      checksum/config: bf2ad27453a7deeb74c2e0b177154649cb6cf292a31b80855c92d28f6a141134
                    prometheus.io/path: /q/metrics
                    prometheus.io/port: 8080
                    prometheus.io/scheme: http
                    prometheus.io/scrape: true
  Service Account:  kaap
  Containers:
   kaap:
    Image:      datastax/kaap:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:8080/q/health/live delay=0s timeout=10s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/q/health/ready delay=0s timeout=10s period=30s #success=1 #failure=3
    Environment Variables from:
      kaap  ConfigMap  Optional: false
    Environment:
      KUBERNETES_NAMESPACE:   (v1:metadata.namespace)
    Mounts:                  <none>
  Volumes:                   <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kaap-76dfd8ddf9 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  2m5s  deployment-controller  Scaled up replica set kaap-76dfd8ddf9 to 1
----
--
====

. You've now installed KAAP.
+
By default, when KAAP is installed, the PulsarCluster CRDs are also created.
This setting is defined in the Pulsar operator values.yaml file as `crd: create: true`.
+
. To see the available CRDs:
+
[tabs]
====
Kubectl::
+
--
[source,kubectl]
----
kubectl get crds | grep kaap
----
--

Result::
+
--
[source,console]
----
autorecoveries.kaap.oss.datastax.com           2023-05-12T16:35:59Z
bastions.kaap.oss.datastax.com                 2023-05-12T16:36:00Z
bookkeepers.kaap.oss.datastax.com              2023-05-12T16:36:00Z
brokers.kaap.oss.datastax.com                  2023-05-12T16:36:01Z
functionsworkers.kaap.oss.datastax.com         2023-05-12T16:36:01Z
proxies.kaap.oss.datastax.com                  2023-05-12T16:36:02Z
pulsarclusters.kaap.oss.datastax.com           2023-05-12T16:36:04Z
zookeepers.kaap.oss.datastax.com               2023-05-12T16:36:06Z
----
--
====

== Uninstall

To uninstall the {pulsar-operator}:
[tabs]
====
Helm::
+
--
[source,helm]
----
helm delete kaap
----
--

Result::
+
--
[source,console]
----
release "kaap" uninstalled
----
--
====

== What's next?

* xref:authentication:index.adoc[]
* xref:scaling-components:autoscale-bookies.adoc[]
* xref:resource-sets:index.adoc[]