= Install {pulsar-stack} Helm chart

The {pulsar-stack} Helm chart installs and deploys the operator pod, a {pulsar-short} cluster with a `PulsarCluster` custom resource definition (CRD), and a full Prometheus monitoring stack.

{pulsar-stack} includes the following:

* {product-short}
* Prometheus Stack (Grafana)
* {pulsar-short} Grafana dashboards
* Cert Manager
* Keycloak

For a minimal installation, xref:getting-started:operator.adoc[install {product-short}], which includes only the operator pod and the `PulsarCluster` CRD.

[TIP]
====
If you have an existing {pulsar-short} cluster, you can scan and generate an equivalent `PulsarCluster` CRD.
For more information, see xref:migration:migrate-cluster.adoc[].
====

== Install {pulsar-stack}

Use Helm to install {pulsar-stack}:

. Install the {company} Helm repository:
+
[source,shell]
----
helm repo add kaap https://datastax.github.io/kaap
helm repo update
----

. Install the {pulsar-stack} Helm chart:
+
[source,shell]
----
helm install pulsar kaap/kaap-stack --values helm/examples/dev-cluster/values.yaml
----
+
.Result
[source,console]
----
NAME: kaap-stack
LAST DEPLOYED: Wed Jun 28 15:46:27 2023
NAMESPACE: pulsar-cluster
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

. Ensure kaap-stack is up and running:
+
[source,shell]
----
kubectl get deployment
----
+
.Result
[source,console]
----
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
kaap                                  1/1     1            1           5m19s
pulsar-autorecovery                   1/1     1            1           3m19s
pulsar-bastion                        1/1     1            1           3m19s
pulsar-grafana                        1/1     1            1           5m19s
pulsar-kube-prometheus-sta-operator   1/1     1            1           5m19s
pulsar-kube-state-metrics             1/1     1            1           5m19s
pulsar-proxy                          1/1     1            1           3m19s
----

. Describe the deployment:
+
[source,shell]
----
kubectl describe deployment kaap-stack
----
+
.Result
[source,console]
----
Name:                   kaap-stack
Namespace:              pulsar-cluster
CreationTimestamp:      Wed, 28 Jun 2023 16:03:51 -0400
Labels:                 app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=kaap-stack
                        helm.sh/chart=kaap-stack-0.1.0
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: kaap-stack
                        meta.helm.sh/release-namespace: pulsar-cluster
                        prometheus.io/path: /q/metrics
                        prometheus.io/port: 8080
                        prometheus.io/scheme: http
                        prometheus.io/scrape: true
Selector:               app.kubernetes.io/name=kaap-stack
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/name=kaap-stack
  Annotations:      checksum/config: bf2ad27453a7deeb74c2e0b177154649cb6cf292a31b80855c92d28f6a141134
                    prometheus.io/path: /q/metrics
                    prometheus.io/port: 8080
                    prometheus.io/scheme: http
                    prometheus.io/scrape: true
  Service Account: kaap
  Containers:
   kaap:
    Image:      datastax/kaap:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:8080/q/health/live delay=0s timeout=10s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/q/health/ready delay=0s timeout=10s period=30s #success=1 #failure=3
    Environment Variables from:
      kaap  ConfigMap  Optional: false
    Environment:
      KUBERNETES_NAMESPACE: (v1:metadata.namespace)
    Mounts:                  <none>
  Volumes:                   <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   kaap-76dfd8ddf9 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  12m   deployment-controller  Scaled up replica set kaap-76dfd8ddf9 to 1
----

== Uninstall

Uninstall the {pulsar-stack} and the cluster:

[source,shell]
----
helm uninstall kaap-stack
----

.Result
[source,console]
----
release "kaap-stack" uninstalled
----

== Next steps

* xref:authentication:auth-jwt.adoc[]
* xref:authentication:auth-tls.adoc[]
* xref:scaling-components:autoscale-bookies.adoc[]
* xref:resource-sets:index.adoc[]