= Migrate existing cluster to {product-short}

Migrating an existing {pulsar-reg} cluster to one controlled by the {product-short} is a manual process, but {product-short} has a built-in migration tool to support this process.

The migration tool is a CLI application that connects to an existing {pulsar} cluster and generates a valid and equivalent `PulsarCluster` custom resource definition (CRD).
The migration tool simulates what would happen if the generated `PulsarCluster` would be submitted, retrieves the Kubernetes resources that would be created, and compares them with the existing cluster's resources, generating a detailed HTML report.
You can then examine the report and decide if you want to proceed with the cluster migration, or if you need to make some changes first.

== Prerequisites

* Java 17
* An existing {pulsar} cluster
* Migration-tool JAR downloaded from the https://github.com/datastax/kaap/releases[latest release].

== Scan and generate cluster CRDs

. Create an input file called `input-cluster-specs.yaml` with the following content:
+
[source,yaml,subs="+quotes"]
----
context: **CONTEXT_NAME**
namespace: **NAMESPACE**
clusterName: **CLUSTER_NAME**
----

.. To retrieve the `context`:
+
[source,shell]
----
kubectl config get-contexts
----
+
.Result
[source,console]
----
CURRENT   NAME                                         CLUSTER                                      AUTHINFO                                     NAMESPACE
*         gke_gcp-techpubs_us-east1-b_pulsar-cluster   gke_gcp-techpubs_us-east1-b_pulsar-cluster   gke_gcp-techpubs_us-east1-b_pulsar-cluster   pulsar-cluster
----
+
Before running the migration tool, {company} recommends switching to K8's current context and ensuring connectivity, such as with `kubectl get pods`.

.. The `namespace` is the namespace with the {pulsar} resources you wish to scan.

.. The `clusterName` is the prefix of each pod.
For example, if the broker pod is `pulsar-prod-cluster-broker-0`, then the `clusterName` is `pulsar-prod-cluster`.

. After you've added the retrieved values to `input-cluster-specs.yaml`, generate the report:
+
[source,shell]
----
java -jar migration-tool.jar generate -i input-cluster-specs.yaml -o output
----

. Find the link to the generated report in the logs, open the generated report in your browser, and then examine the differences between the existing cluster and the {product-short}.
+
If everything looks good, proceed to the <<migration-procedure,migration procedure>>.
+
If you need to change the generated CRD and simulate the migration again, run the following command after making the necessary changes:
+
[source,shell,subs="+quotes"]
----
java -jar migration-tool.jar diff -d output/**CONTEXT_NAME**
----

[#migration-procedure]
== Migration procedure

. Create a new `values.yaml` file for the operator.

. In the `pulsar-operator.cluster` section, enter the generated CRD spec:
+
[source,yaml,subs="+quotes"]
----
pulsar-operator:
    cluster:
        create: true
        name: **CLUSTER_NAME**
        spec:
            **GENERATED_SPEC_FROM_CRD**
----

. Install the operator release with the new `values.yaml` file:
+
[source,shell,subs="+quotes"]
----
helm install pulsar kaap/kaap-stack --values **PATH/TO/VALUES.YAML**
----

. Wait for the PulsarCluster status to be in a Ready state, which indicates that the operator has assumed control of the cluster.
Since the generated resources will match the existing cluster's resources, the following behaviors are expected:
+
* The operator doesn't create any new resources.
* The operator doesn't delete any existing resources.
* The operator doesn't restart every statefulset/deployment.
This is done in a safe manner using the operator's staged upgrades feature.

== Cleanup

. Delete the existing chart release:
+
[source,shell,subs="+quotes"]
----
kubectl delete secret -l name=**EXISTING_RELEASE_NAME**,owner=helm
----

. Clean up Helm annotations and labels:
+
* You can safely remove the following annotations:
** `meta.helm.sh/release-name`
** `meta.helm.sh/release-namespace`
* You can safely remove the following labels:
** `app.kubernetes.io/managed-by`
** `chart`
** `release`
** `heritage`

== Next steps

Now that you've migrated your existing cluster to the operator, you can start using the operator's features to manage your cluster.

* xref:scaling-components:autoscale-bookies.adoc[Auto-scale bookies]
* xref:scaling-components:autoscale-brokers.adoc[Auto-scale brokers]
* xref:ROOT:resource-sets.adoc[Resource sets]