= Resource Sets and Racks

The operator allows you to create multiple sets of Pulsar proxies, brokers, and bookies, called resource sets.
Each set is a dedicated deployment/statefulset with its own service and configmap.
When multiple sets are specified, an umbrella service is created as the main entrypoint of the cluster, but otherwise, a dedicated service is created for each set. You can customize the service per set - for example, you might assign different DNS domains for each resource set.

Resource sets are a very powerful addition to a {pulsar-operator}-managed cluster, allowing you to create different configurations for the same components. For example, you might dedicate a set of brokers to a single customer, or you can create a set of brokers with a different configuration for testing purposes.

Racks, proxies, bookies, and pods can likewise be created as resource sets with their own configurations.

* xref:resource-sets:racks.adoc[]
* xref:resource-sets:proxies.adoc[]
* xref:resource-sets:bookies.adoc[]
* xref:resource-sets:pods.adoc[]

== Install Operator with resource sets enabled
[source,helm]
----
helm install pulsar-operator helm/pulsar-operator \
    --values helm/examples/resource-sets/values.yaml
----