= TLS authentication

You can enable TLS for each component in the Pulsar cluster, or you can enable it only for specific components.
Each component has its own dedicated configuration section, but they're all under the `global.tls` section.
Once the TLS setup is done, the operator updates the components configuration to use TLS.

To setup a zero-trust cluster with TLS, set `enabled` to `true` for each component:

[source,yaml]
----
global:
    tls:
      enabled: true
      zookeeper:
        enabled: true
        secretName: zk-tls
      bookkeeper:
        enabled: true
        secretName: bk-tls
      autorecovery:
        enabled: true
        secretName: autorecovery-tls
      proxy:
        enabled: true
        enabledWithBroker: true
        secretName: proxy-tls
      broker:
        enabled: true
        secretName: broker-tls
      functionsWorker:
        enabled: true
        enabledWithBroker: true
        secretName: fnw-tls
----

Note that each component has its own secret name.
The secret name can be auto provisioned by the operator using `cert-manager`. You can share the same certificate across multiple components, although it's not a recommended practice for security reasons.

The secret must follow the [cert-manager Certificate](https://cert-manager.io/docs/concepts/certificate/) structure:
- `tls.crt`: the certificate
- `tls.key`: the private key

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: pulsar-tls
data:
  tls.crt: <base64 encoded certificate>
  tls.key: <base64 encoded key>
----

The operator only needs to know the secret name and it will automatically use it as is.
In some cases, like test clusters, you might wish to generate self signed certificates.
The operator integrates well with cert-manager to generate a self-signed CA and all the needed certificates.

In order to enable the certificate provisioning you have to configure it in the `global.tls` section.
[source,yaml]
----
global:
    tls:
        certProvisioner:
            selfSigned:
              enabled: true
              perComponent: true
              zookeeper:
                generate: true
              broker:
                generate: true
              bookkeeper:
                generate: true
              autorecovery:
                generate: true
              proxy:
                generate: true
              functionsWorker:
                generate: true
----
This will generate all the secrets needed by the components. The name of each secret is gathered from the `secretName` configured.

The repository contains examples for [real TLS example with acme](https://github.com/riptano/pulsar-operator/tree/main/helm/examples/cert-manager-acme) and [self-signed certificates](https://github.com/riptano/pulsar-operator/tree/main/helm/examples/cert-manager-self-signed).