= Install and Deploy

You need to have an existing Pulsar cluster up and running first - might we suggest our DataStax Pulsar Helm chart?
[source,helm]
----
helm repo add datastax-pulsar https://datastax.github.io/pulsar-helm-chart
helm repo update
curl -LOs https://datastax.github.io/pulsar-helm-chart/examples/dev-values.yaml
helm install pulsar -f dev-values.yaml datastax-pulsar/pulsar
----
[TIP]
====
Learn more about installing the Luna Streaming Helm chart xref:install-upgrade:quickstart-helm-installs.adoc[here].
====

. The {pulsar-operator} Helm chart is currently only available privately.
Download it here: https://github.com/riptano/pulsar-operator/releases/download/pulsar-operator-0.0.2/pulsar-operator-0.0.2.tgz
. Install the {pulsar-operator} Helm chart:
+
[source,helm]
----
helm install pulsar-operator pulsar-operator-0.0.2.tgz
...
NAME: pulsar-operator
LAST DEPLOYED: Wed Mar 15 12:22:29 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

. Ensure pulsar-operator is up and running:

[source,helm]
----
kubectl get deployment
----

Result:

[source,plain]
----
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
pulsar-operator   1/1     1            1           13m
----

[source,bash]
----
kubectl describe deployment pulsar-operator
----

result
[source,plain]
----
Name:                   pulsar-operator
Namespace:              pulsar-stack
CreationTimestamp:      Tue, 28 Mar 2023 22:14:35 -0400
Labels:                 app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=pulsar-operator
                        app.kubernetes.io/version=
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: pulsar-operator
                        meta.helm.sh/release-namespace: pulsar-stack
                        prometheus.io/path: /q/metrics
                        prometheus.io/port: 8080
                        prometheus.io/scheme: http
                        prometheus.io/scrape: true
Selector:               app.kubernetes.io/name=pulsar-operator,app.kubernetes.io/version=
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/name=pulsar-operator
                    app.kubernetes.io/version=
  Annotations:      prometheus.io/path: /q/metrics
                    prometheus.io/port: 8080
                    prometheus.io/scheme: http
                    prometheus.io/scrape: true
  Service Account:  pulsar-operator
  Containers:
   pulsar-operator:
    Image:      datastax/lunastreaming-operator:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:8080/q/health/live delay=0s timeout=10s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/q/health/ready delay=0s timeout=10s period=30s #success=1 #failure=3
    Environment:
      KUBERNETES_NAMESPACE:   (v1:metadata.namespace)
    Mounts:                  <none>
  Volumes:                   <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   pulsar-operator-7975c847d4 (1/1 replicas created)
Events:
  Type    Reason             Age    From                   Message
  ----    ------             ----   ----                   -------
  Normal  ScalingReplicaSet  5m48s  deployment-controller  Scaled up replica set pulsar-operator-7975c847d4 to 1
----

You've now installed Pulsar Operator within your Pulsar cluster.

To uninstall the operator:
[source,bash]
----
helm delete pulsar-operator
----

result
----
release "pulsar-operator" uninstalled
----


== {pulsar-stack}

Need more monitoring and management capabilities?
Check out the {pulsar-stack}.
It includes:

* Pulsar Operator
* Prometheus Stack (Grafana)
* Pulsar Grafana dashboards
* Cert Manager
* Keycloak

To install a PulsarCluster with the Pulsar stack included:
[source,bash]
----
helm install pulsar pulsar-stack-0.0.2.tgz --set pulsar-operator.cluster.create=true
----

Wait for the cluster to be up and running:

[source,bash]
----
kubectl wait pulsar pulsar --for condition=Ready=True --timeout=240s
----

To check the status of your deployments:

[source,bash]
----
kubectl get deployment
----

result
----
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
pulsar-autorecovery   1/1     1            1           24m
pulsar-bastion        1/1     1            1           24m
pulsar-operator       1/1     1            1           27m
pulsar-proxy          2/3     3            2           24m
----

And describe the pulsar-operator deployment:

[source,bash]
----
kubectl describe deployment pulsar-operator
----

result
----
Name:                   pulsar-operator
Namespace:              pulsar-stack
CreationTimestamp:      Tue, 28 Mar 2023 21:38:51 -0400
Labels:                 app.kubernetes.io/managed-by=Helm
                        app.kubernetes.io/name=pulsar-operator
                        app.kubernetes.io/version=
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: pulsar
                        meta.helm.sh/release-namespace: pulsar-stack
                        prometheus.io/path: /q/metrics
                        prometheus.io/port: 8080
                        prometheus.io/scheme: http
                        prometheus.io/scrape: true
Selector:               app.kubernetes.io/name=pulsar-operator,app.kubernetes.io/version=
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/name=pulsar-operator
                    app.kubernetes.io/version=
  Annotations:      prometheus.io/path: /q/metrics
                    prometheus.io/port: 8080
                    prometheus.io/scheme: http
                    prometheus.io/scrape: true
  Service Account:  pulsar-operator
  Containers:
   pulsar-operator:
    Image:      datastax/lunastreaming-operator:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:8080/q/health/live delay=0s timeout=10s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/q/health/ready delay=0s timeout=10s period=30s #success=1 #failure=3
    Environment:
      KUBERNETES_NAMESPACE:   (v1:metadata.namespace)
    Mounts:                  <none>
  Volumes:                   <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   pulsar-operator-7975c847d4 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  27m   deployment-controller  Scaled up replica set pulsar-operator-7975c847d4 to 1
----


To uninstall the operator and the cluster:
[source,bash]
----
helm delete pulsar
----

result
----
release "pulsar" uninstalled
----