= Scale the {pulsar-short} Broker with a {kafka-short} client workload
:navtitle: {kafka-short}

This guide demonstrates how to configure and run an {kafka-reg} workload on an {pulsar-reg} cluster with the Broker Auto Scaling feature.

Support for the {kafka-short} wire protocol is provided by xref:starlight-for-kafka:ROOT:index.adoc[{starlight-kafka}].

The client work load is generated using the basic {kafka-short} performance tools.

. Install the {product-short} and a {pulsar-short} cluster.
+
The following example xref:getting-started:stack.adoc[installs {pulsar-stack}] with the {kafka-short} protocol enabled:
+
[source,shell]
----
helm install pos helm/pulsar-stack --values helm/examples/kafka/values.yaml
----
+
The {kafka-short} protocol is controlled in the deployment's `values.yaml` file:
+
[source,yaml]
----
kafka:
        enabled: true
    autoscaler:
        enabled: true
        periodMs: 20000
        min: 2
        max: 10
        lowerCpuThreshold: 0.2
        higherCpuThreshold: 0.4
        scaleUpBy: 1
        scaleDownBy: 1
        stabilizationWindowMs: 120000
    config: {}
----
+
Additionally, you can proxy the {kafka-short} connection in the {pulsar-short} Proxy with `kafka:enabled:true`:
+
[source,yaml]
----
proxy:
        replicas: 1
        resources:
          requests:
            cpu: "0.2"
            memory: "128Mi"
        kafka:
          enabled: true
        config: {}
----

. Deploy the {kafka-short} producers:
+
[source,shell]
----
kubectl apply -f helm/examples/kafka/kafka-producer-perf.yaml
----

. Get the logs of the {kafka-short} producers:
+
[source,shell]
----
kubectl logs -f deploy/kafka-client-producer
----

. Deploy the {kafka-short} consumers:
+
[source,shell]
----
kubectl apply -f helm/examples/kafka/kafka-consumer-perf.yaml
----

. Get the logs of the {kafka-short} consumers:
+
[source,shell]
----
kubectl logs -f deploy/kafka-client-consumer
----

. Scale the client workloads:
+
.. Open a terminal, and then get the logs of the {product-short}:
+
[source,shell]
----
kubectl logs -f deploy/pulsar-operator
----
+
.. Use `kubectl` to scale the client applications up and down:
+
[source,shell]
----
kubectl scale deploy/kafka-client-consumer --replicas 10
----
+
As the load increases, the {product-short} scales out the Broker STS.