= Broker autoscaler

The operator scales the number of broker pods in a cluster up and down based on current CPU usage.
The CPU usage of each broker is checked at the Pulsar load balancer, not just at the Kubenetes pod level. This means that the operator can scale brokers based on the CPU usage of all brokers in the cluster, not just the CPU usage of a single broker pod.
When the operator sees that the Pulsar load balancer is having trouble finding brokers to assign topic bundles to, it will scale up the number of brokers to handle the load.
When the operator sees that the CPU usage of all brokers is low, it will scale down the number of brokers to save resources.
CPU usage is tightly coupled to traffic, so you can expect to see significant scaling activity with broker autoscaler enabled. This value can be controlled with the `stabilizationWindowMs` parameter, which tells the operator how long to wait between scaling events.

== Install Operator with broker autoscaler enabled
[source,bash]
----
helm install pulsar-operator helm/pulsar-stack \
    --values helm/examples/broker-autoscaling/values.yaml
----
The operator's thresholds are set in the values.yaml file. +
[source,helm]
----
      broker:
        replicas: 2
        autoscaler:
          enabled: true
          periodMs: 20000
          min: 2
          max: 10
          lowerCpuThreshold: 0.4
          higherCpuThreshold: 0.8
          scaleUpBy: 1
          scaleDownBy: 1
          stabilizationWindowMs: 60000
----
.Broker autoscaler configuration
[cols=4*,options="header"]
|===
|Name
|Type
|Description
|Notes

|enabled
|Boolean
|Enable autoscaling for brokers.
|

|higherCpuThreshold
|Double
|The threshold to trigger a scale up. The autoscaler will scale up if all the brokers' CPU usage is higher than this threshold.
|Default is 0.8. Min 0.0, Max 1.0.

|lowerCpuThreshold
|Double
|The threshold to trigger a scale down. The autoscaler will scale down if all the brokers' CPU usage is lower than this threshold.
|Default is 0.4. Min(0.0), Max(1.0)

|max
|Integer
|Maximum number of brokers. If the number of brokers is equal to this value, the autoscaler will never scale up.
|Min 1.

|min
|Integer
|Minimum number of brokers. If the number of brokers is equal to this value, the autoscaler will never scale down.
|Min 1.

|periodMs
|Long
|The interval in milliseconds between two consecutive autoscaling checks.
|Minimum value is 1000 ms.

|scaleDownBy
|Integer
|The number of brokers to remove at each scale down.
|Default is 1. Min 1.

|scaleUpBy
|Integer
|The number of brokers to add at each scale up.
|Default is 1. Min 1.

|stabilizationWindowMs
|Long
|The stabilization window restricts rapid changes in replica count when the metrics used for scaling are fluctuating. The autoscaling algorithm uses this window to infer a previous desired state and avoid unwanted changes to workload scale.
|Default value is 5 minutes after the pod's state is Ready.
|===
